export const allPmKotoba = [
  // BAB 1 — Keamanan Pangan & Mikrobiologi
  { id: 1, kanji: '食品安全', reading: 'しょくひんあんぜん', meaning: 'Keamanan Pangan' },
  { id: 2, kanji: '品質', reading: 'ひんしつ', meaning: 'Kualitas' },
  { id: 3, kanji: '管理', reading: 'かんり', meaning: 'Manajemen' },
  { id: 4, kanji: '知識', reading: 'ちしき', meaning: 'Pengetahuan' },
  { id: 5, kanji: '食品', reading: 'しょくひん', meaning: 'Makanan' },
  { id: 6, kanji: '食中毒', reading: 'しょくちゅうどく', meaning: 'Keracunan Makanan' },
  { id: 7, kanji: '防止', reading: 'ぼうし', meaning: 'Pencegahan' },
  { id: 8, kanji: '原則', reading: 'げんそく', meaning: 'Prinsip' },
  { id: 9, kanji: '基礎知識', reading: 'きそちしき', meaning: 'Pengetahuan Dasar' },
  { id: 10, kanji: '微生物', reading: 'びせいぶつ', meaning: 'Mikroorganisme' },
  { id: 11, kanji: '増殖する', reading: 'ぞうしょくする', meaning: 'Berkembang biak' },
  { id: 12, kanji: '温度', reading: 'おんど', meaning: 'Suhu' },
  { id: 13, kanji: '水分', reading: 'すいぶん', meaning: 'Kelembapan' },
  { id: 14, kanji: '栄養分', reading: 'えいようぶん', meaning: 'Nutrisi' },
  { id: 15, kanji: '製造', reading: 'せいぞう', meaning: 'Manufaktur' },
  { id: 16, kanji: '消費者', reading: 'しょうひしゃ', meaning: 'Konsumen' },
  { id: 17, kanji: '不信感', reading: 'ふしんかん', meaning: 'Ketidakpercayaan' },
  { id: 18, kanji: '原材料', reading: 'げんざいりょう', meaning: 'Bahan Baku' },
  { id: 19, kanji: '製造環境', reading: 'せいぞうかんきょう', meaning: 'Lingkungan Manufaktur' },
  { id: 20, kanji: '衛生', reading: 'えいせい', meaning: 'Kebersihan/Higienis' },
  { id: 21, kanji: '取り扱い', reading: 'とりあつかい', meaning: 'Penanganan' },
  { id: 22, kanji: '条件', reading: 'じょうけん', meaning: 'Syarat' },
  { id: 23, kanji: '受入', reading: 'うけいれ', meaning: 'Penerimaan' },
  { id: 24, kanji: '衛生管理', reading: 'えいせいかんり', meaning: 'Manajemen Kebersihan' },
  { id: 25, kanji: '化学物質', reading: 'かがくぶっしつ', meaning: 'Bahan Kimia' },
  { id: 26, kanji: '飲食品', reading: 'いんしょくひん', meaning: 'Makanan dan Minuman' },
  { id: 27, kanji: '健康障害', reading: 'けんこうしょうがい', meaning: 'Bahaya Kesehatan' },
  { id: 28, kanji: '下痢', reading: 'げり', meaning: 'Diare' },
  { id: 29, kanji: '原因', reading: 'げんいん', meaning: 'Penyebab' },
  { id: 30, kanji: '細菌', reading: 'さいきん', meaning: 'Bakteri' },
  { id: 31, kanji: '分類', reading: 'ぶんるい', meaning: 'Klasifikasi' },
  { id: 32, kanji: '細胞', reading: 'さいぼう', meaning: 'Sel' },
  { id: 33, kanji: '毒素', reading: 'どくそ', meaning: 'Racun' },
  { id: 34, kanji: '牡蠣', reading: 'かき', meaning: 'Kerang Tiram' },
  { id: 35, kanji: '症状', reading: 'しょうじょう', meaning: 'Gejala' },
  { id: 36, kanji: '予防対策', reading: 'よぼうたいさく', meaning: 'Tindakan Pencegahan' },
  { id: 37, kanji: '腹痛', reading: 'ふくつう', meaning: 'Sakit Perut' },
  { id: 38, kanji: '発熱', reading: 'はつねつ', meaning: 'Demam' },
  { id: 39, kanji: '食肉', reading: 'しょくにく', meaning: 'Daging' },
  { id: 40, kanji: '鶏卵', reading: 'けいらん', meaning: 'Telur Ayam' },
  { id: 41, kanji: '加熱します', reading: 'かねつします', meaning: 'Memanaskan' },
  { id: 42, kanji: '洗浄する', reading: 'せんじょうする', meaning: 'Membersihkan' },
  { id: 43, kanji: '嘔吐', reading: 'おうと', meaning: 'Muntah' },
  { id: 44, kanji: '吐気', reading: 'はきけ', meaning: 'Mual' },
  { id: 45, kanji: '保存します', reading: 'ほぞんします', meaning: 'Menyimpan' },
  { id: 46, kanji: '煮物', reading: 'にもの', meaning: 'Makanan Rebus' },
  { id: 47, kanji: '芽胞', reading: 'がほう', meaning: 'Spora' },
  { id: 48, kanji: '冷却', reading: 'れいきゃく', meaning: 'Mendinginkan' },
  { id: 49, kanji: '高温', reading: 'こうおん', meaning: 'Suhu Tinggi' },
  { id: 50, kanji: '低温', reading: 'ていおん', meaning: 'Suhu Rendah' },
  { id: 51, kanji: '室温', reading: 'しつおん', meaning: 'Suhu Ruangan' },
  { id: 52, kanji: '器具', reading: 'きぐ', meaning: 'Instrumen/Alat' },
  { id: 53, kanji: '装置', reading: 'そうち', meaning: 'Perangkat' },
  { id: 54, kanji: '機械', reading: 'きかい', meaning: 'Mesin' },
  { id: 55, kanji: '乾燥します', reading: 'かんそうします', meaning: 'Mengeringkan' },
  { id: 56, kanji: '豆', reading: 'まめ', meaning: 'Kacang' },
  { id: 57, kanji: '穀類', reading: 'こくるい', meaning: 'Biji-bijian/Sereal' },
  { id: 58, kanji: '防ぎます', reading: 'ふせぎます', meaning: 'Mencegah' },
  { id: 59, kanji: '血便', reading: 'けつべん', meaning: 'Berak Darah' },
  // BAB 2 — Manajemen Kebersihan
  { id: 60, kanji: '健康管理', reading: 'けんこうかんり', meaning: 'Manajemen Kesehatan' },
  { id: 61, kanji: '作業場', reading: 'さぎょうじょう', meaning: 'Tempat Kerja' },
  { id: 62, kanji: '体調', reading: 'たいちょう', meaning: 'Kondisi Tubuh' },
  { id: 63, kanji: '責任者', reading: 'せきにんしゃ', meaning: 'Penanggung Jawab' },
  { id: 64, kanji: '報告する', reading: 'ほうこくする', meaning: 'Melapor' },
  { id: 65, kanji: '指示', reading: 'しじ', meaning: 'Perintah' },
  { id: 66, kanji: '爪', reading: 'つめ', meaning: 'Kuku' },
  { id: 67, kanji: '宝石類', reading: 'ほうせきるい', meaning: 'Perhiasan' },
  { id: 68, kanji: '装飾品', reading: 'そうしょくひん', meaning: 'Aksesoris' },
  { id: 69, kanji: '作業服', reading: 'さぎょうふく', meaning: 'Pakaian Kerja' },
  { id: 70, kanji: '清潔な', reading: 'せいけつな', meaning: 'Bersih' },
  { id: 71, kanji: '汚れた', reading: 'よごれた', meaning: 'Kotor' },
  { id: 72, kanji: '洗濯します', reading: 'せんたくします', meaning: 'Mencuci Pakaian' },
  { id: 73, kanji: '帽子', reading: 'ぼうし', meaning: 'Topi' },
  { id: 74, kanji: '洗髪', reading: 'せんぱつ', meaning: 'Keramas' },
  { id: 75, kanji: '香水', reading: 'こうすい', meaning: 'Parfum' },
  { id: 76, kanji: '指輪', reading: 'ゆびわ', meaning: 'Cincin' },
  { id: 77, kanji: '袖ゴム', reading: 'そでごむ', meaning: 'Lengan Baju Karet' },
  { id: 78, kanji: '確認します', reading: 'かくにんします', meaning: 'Mengkonfirmasi' },
  { id: 79, kanji: '毛髪', reading: 'もうはつ', meaning: 'Rambut' },
  { id: 80, kanji: '埃', reading: 'ほこり', meaning: 'Debu' },
  { id: 81, kanji: '消毒液', reading: 'しょうどくえき', meaning: 'Cairan Antiseptik' },
  { id: 82, kanji: '消毒する', reading: 'しょうどくする', meaning: 'Mensterilkan' },
  { id: 83, kanji: '作業靴', reading: 'さぎょうぐつ', meaning: 'Sepatu Kerja' },
  { id: 84, kanji: '通勤靴', reading: 'つうきんぐつ', meaning: 'Sepatu Biasa' },
  { id: 85, kanji: '汚染区', reading: 'おせんく', meaning: 'Area Terkontaminasi' },
  { id: 86, kanji: '担当', reading: 'たんとう', meaning: 'Posisi/Petugas' },
  { id: 87, kanji: '不備', reading: 'ふび', meaning: 'Cacat/Rusak' },
  { id: 88, kanji: '点検表', reading: 'てんけんひょう', meaning: 'Daftar Pemeriksaan' },
  { id: 89, kanji: '洗浄剤', reading: 'せんじょうざい', meaning: 'Bahan Pembersih' },
  { id: 90, kanji: '殺菌剤', reading: 'さっきんざい', meaning: 'Bahan Antiseptik' },
  { id: 91, kanji: '洗浄', reading: 'せんじょう', meaning: 'Pembersihan' },
  { id: 92, kanji: '殺菌', reading: 'さっきん', meaning: 'Pensterilisasian' },
  { id: 93, kanji: '注意事項', reading: 'ちゅういじこう', meaning: 'Tindakan Pencegahan' },
  { id: 94, kanji: '合図', reading: 'あいず', meaning: 'Tanda/Isyarat' },
  { id: 95, kanji: '危険', reading: 'きけん', meaning: 'Bahaya' },
  { id: 96, kanji: '異常', reading: 'いじょう', meaning: 'Tidak Normal' },
  { id: 97, kanji: '停電', reading: 'ていでん', meaning: 'Mati Listrik' },
  { id: 98, kanji: '製品', reading: 'せいひん', meaning: 'Produk' },
  { id: 99, kanji: '製造ライン', reading: 'せいぞうライン', meaning: 'Jalur Produksi' },
  { id: 100, kanji: '整理', reading: 'せいり', meaning: 'Pilah (5S)' },
  { id: 101, kanji: '整頓', reading: 'せいとん', meaning: 'Rapikan (5S)' },
  { id: 102, kanji: '清掃', reading: 'せいそう', meaning: 'Resik (5S)' },
  { id: 103, kanji: '清潔', reading: 'せいけつ', meaning: 'Bersih (5S)' },
  { id: 104, kanji: '習慣', reading: 'しゅうかん', meaning: 'Kebiasaan (5S)' },
  { id: 105, kanji: '異物混入', reading: 'いぶつこんにゅう', meaning: 'Kontaminasi Benda Asing' },
  { id: 106, kanji: '金属', reading: 'きんぞく', meaning: 'Logam' },
  { id: 107, kanji: '髪の毛', reading: 'かみのけ', meaning: 'Rambut' },
  // BAB 3 — Proses Produksi
  { id: 108, kanji: '考え方', reading: 'かんがえかた', meaning: 'Cara Berpikir' },
  { id: 109, kanji: '製造工程', reading: 'せいぞうこうてい', meaning: 'Proses Produksi' },
  { id: 110, kanji: '段階', reading: 'だんかい', meaning: 'Langkah/Tahap' },
  { id: 111, kanji: '危害', reading: 'きがい', meaning: 'Bahaya' },
  { id: 112, kanji: '危害分析', reading: 'きがいぶんせき', meaning: 'Analisis Bahaya' },
  { id: 113, kanji: '検査結果', reading: 'けんさけっか', meaning: 'Hasil Inspeksi' },
  { id: 114, kanji: '資料', reading: 'しりょう', meaning: 'Dokumen' },
  { id: 115, kanji: '検査', reading: 'けんさ', meaning: 'Inspeksi' },
  { id: 116, kanji: '冷蔵庫', reading: 'れいぞうこ', meaning: 'Lemari Pendingin' },
  { id: 117, kanji: '冷凍庫', reading: 'れいとうこ', meaning: 'Lemari Pembeku' },
  { id: 118, kanji: '規定', reading: 'きてい', meaning: 'Peraturan' },
  { id: 119, kanji: '食品衛生法', reading: 'しょくひんえいせいほう', meaning: 'UU Sanitasi Makanan' },
  { id: 120, kanji: '測定', reading: 'そくてい', meaning: 'Pengukuran' },
  { id: 121, kanji: '記録する', reading: 'きろくする', meaning: 'Mencatat' },
  { id: 122, kanji: '加熱工程', reading: 'かねつこうてい', meaning: 'Proses Pemanasan' },
  { id: 123, kanji: '芽胞菌', reading: 'がほうきん', meaning: 'Bakteri Pembawa Spora' },
  { id: 124, kanji: '対象', reading: 'たいしょう', meaning: 'Target' },
  { id: 125, kanji: '冷却工程', reading: 'れいきゃくこうてい', meaning: 'Proses Pendinginan' },
  { id: 126, kanji: '冷水', reading: 'れいすい', meaning: 'Air Dingin' },
  { id: 127, kanji: '凍結工程', reading: 'とうけつこうてい', meaning: 'Proses Pembekuan' },
  { id: 128, kanji: '風味', reading: 'ふうみ', meaning: 'Cita Rasa' },
  { id: 129, kanji: '短時間', reading: 'たんじかん', meaning: 'Waktu Singkat' },
  { id: 130, kanji: '包装工程', reading: 'ほうそうこうてい', meaning: 'Proses Pengemasan' },
  { id: 131, kanji: '金属検出器', reading: 'きんぞくけんしゅつき', meaning: 'Detektor Logam' },
  { id: 132, kanji: '期限表示', reading: 'きげんひょうじ', meaning: 'Tanggal Kadaluwarsa' },
  { id: 133, kanji: '基準', reading: 'きじゅん', meaning: 'Standar' },
  { id: 134, kanji: '法律', reading: 'ほうりつ', meaning: 'Hukum' },
  { id: 135, kanji: '定めます', reading: 'さだめます', meaning: 'Menetapkan' },
  { id: 136, kanji: '菌数', reading: 'きんすう', meaning: 'Jumlah Bakteri' },
  { id: 137, kanji: '製造日', reading: 'せいぞうび', meaning: 'Tanggal Produksi' },
  { id: 138, kanji: '冷蔵車', reading: 'れいぞうしゃ', meaning: 'Truk Pendingin' },
  { id: 139, kanji: '冷凍車', reading: 'れいとうしゃ', meaning: 'Truk Pembeku' },
  { id: 140, kanji: 'アレルギー', reading: 'アレルギー', meaning: 'Alergi' },
  { id: 141, kanji: '特定原材料', reading: 'とくていげんざいりょう', meaning: 'Bahan Baku Khusus (Alergen)' },
  { id: 142, kanji: '乳', reading: 'にゅう', meaning: 'Susu' },
  { id: 143, kanji: '落花生', reading: 'らっかせい', meaning: 'Kacang Tanah' },
  { id: 144, kanji: '大豆', reading: 'だいず', meaning: 'Kedelai' },
  { id: 145, kanji: '交差汚染', reading: 'こうさおせん', meaning: 'Kontaminasi Silang' },
  { id: 146, kanji: '容器', reading: 'ようき', meaning: 'Wadah' },
  { id: 147, kanji: '薬剤', reading: 'やくざい', meaning: 'Bahan Kimia/Obat' },
  { id: 148, kanji: '保管場所', reading: 'ほかんばしょ', meaning: 'Tempat Penyimpanan' },
  { id: 149, kanji: '義務', reading: 'ぎむ', meaning: 'Kewajiban' },
  { id: 150, kanji: '表示', reading: 'ひょうじ', meaning: 'Label/Tanda' },
  // BAB 4 — HACCP
  { id: 151, kanji: '略語', reading: 'りゃくご', meaning: 'Singkatan' },
  { id: 152, kanji: '管理点', reading: 'かんりてん', meaning: 'Titik Kontrol' },
  { id: 153, kanji: '最終製品', reading: 'さいしゅうせいひん', meaning: 'Produk Akhir' },
  { id: 154, kanji: '出荷', reading: 'しゅっか', meaning: 'Pengiriman' },
  { id: 155, kanji: '重要管理点', reading: 'じゅうようかんりてん', meaning: 'Titik Kontrol Kritis (CCP)' },
  { id: 156, kanji: '農薬', reading: 'のうやく', meaning: 'Pestisida' },
  { id: 157, kanji: '抗生物質', reading: 'こうせいぶしつ', meaning: 'Antibiotik' },
  { id: 158, kanji: '決定', reading: 'けってい', meaning: 'Penentuan' },
  { id: 159, kanji: '加熱殺菌工程', reading: 'かねつさっきんこうてい', meaning: 'Sterilisasi Panas' },
  { id: 160, kanji: '管理基準', reading: 'かんりきじゅん', meaning: 'Standar Manajemen' },
  { id: 161, kanji: '設定', reading: 'せってい', meaning: 'Pengaturan' },
  { id: 162, kanji: '監視', reading: 'かんし', meaning: 'Pemantauan' },
  { id: 163, kanji: '確保する', reading: 'かくほする', meaning: 'Mengamankan' },
  { id: 164, kanji: '検証方法', reading: 'けんしょうほうほう', meaning: 'Metode Verifikasi' },
  { id: 165, kanji: '保管期間', reading: 'ほかんきかん', meaning: 'Periode Penyimpanan' },
  { id: 166, kanji: '鉄', reading: 'てつ', meaning: 'Besi' },
  { id: 167, kanji: '業務', reading: 'ぎょうむ', meaning: 'Tugas/Pekerjaan' },
  // BAB 5 — Keselamatan Kerja
  { id: 168, kanji: '労働', reading: 'ろうどう', meaning: 'Bekerja' },
  { id: 169, kanji: '労働者', reading: 'ろうどうしゃ', meaning: 'Pekerja' },
  { id: 170, kanji: '事業者', reading: 'じぎょうしゃ', meaning: 'Pelaku Industri' },
  { id: 171, kanji: '労働災害', reading: 'ろうどうさいがい', meaning: 'Kecelakaan Kerja' },
  { id: 172, kanji: '安全装置', reading: 'あんぜんそうち', meaning: 'Perangkat Keamanan' },
  { id: 173, kanji: '転倒', reading: 'てんとう', meaning: 'Terjatuh' },
  { id: 174, kanji: '爆発', reading: 'ばくはつ', meaning: 'Meledak' },
  { id: 175, kanji: '服装', reading: 'ふくそう', meaning: 'Pakaian' },
  { id: 176, kanji: '長袖', reading: 'ながそで', meaning: 'Lengan Panjang' },
  { id: 177, kanji: '刃物', reading: 'はもの', meaning: 'Benda Tajam' },
  { id: 178, kanji: '保護具', reading: 'ほごぐ', meaning: 'Alat Pelindung Diri' },
  { id: 179, kanji: '安全靴', reading: 'あんぜんぐつ', meaning: 'Sepatu Safety' },
  { id: 180, kanji: '食品加工', reading: 'しょくひんかこう', meaning: 'Pengolahan Makanan' },
  { id: 181, kanji: '包丁', reading: 'ほうちょう', meaning: 'Pisau Dapur' },
  { id: 182, kanji: '熱中症', reading: 'ねっちゅうしょう', meaning: 'Heat Stroke' },
  { id: 183, kanji: '睡眠不足', reading: 'すいみんぶそく', meaning: 'Kekurangan Tidur' },
  { id: 184, kanji: '頭痛', reading: 'ずつう', meaning: 'Sakit Kepala' },
  { id: 185, kanji: '痙攣', reading: 'けいれん', meaning: 'Kejang' },
  { id: 186, kanji: '救急車', reading: 'きゅうきゅうしゃ', meaning: 'Ambulance' },
  { id: 187, kanji: '同僚', reading: 'どうりょう', meaning: 'Rekan Kerja' },
  { id: 188, kanji: '二次災害', reading: 'にじさいがい', meaning: 'Kecelakaan Lanjutan' },
  { id: 189, kanji: '被災者', reading: 'ひさいしゃ', meaning: 'Korban' },
  { id: 190, kanji: '呼吸', reading: 'こきゅう', meaning: 'Pernafasan' },
  { id: 191, kanji: '台車', reading: 'だいしゃ', meaning: 'Gerobak' },
  { id: 192, kanji: '通路', reading: 'つうろ', meaning: 'Lorong' },
  { id: 193, kanji: '停止', reading: 'ていし', meaning: 'Berhenti (Mesin)' },
  { id: 194, kanji: '電源', reading: 'でんげん', meaning: 'Tombol Daya' },
  { id: 195, kanji: '整備', reading: 'せいび', meaning: 'Pemeliharaan' },
  { id: 196, kanji: '生産', reading: 'せいさん', meaning: 'Produksi' },
  { id: 197, kanji: '訓練', reading: 'くんれん', meaning: 'Pelatihan' },
  { id: 198, kanji: '避難訓練', reading: 'ひなんくんれん', meaning: 'Latihan Evakuasi' },
  { id: 199, kanji: '保護メガネ', reading: 'ほごメガネ', meaning: 'Kacamata Pelindung' },
  { id: 200, kanji: '腰痛', reading: 'ようつう', meaning: 'Sakit Pinggang' },
  { id: 201, kanji: '体温', reading: 'たいおん', meaning: 'Suhu Tubuh' },
  { id: 202, kanji: '道具', reading: 'どうぐ', meaning: 'Peralatan' },
  { id: 203, kanji: '火災', reading: 'かさい', meaning: 'Kebakaran' },
  { id: 204, kanji: '判断', reading: 'はんだん', meaning: 'Keputusan' },
  { id: 205, kanji: '修理中', reading: 'しゅうりちゅう', meaning: 'Sedang Diperbaiki' },
  { id: 206, kanji: '未熟練作業者', reading: 'みじゅくれんさぎょうしゃ', meaning: 'Pekerja Tidak Terampil' },
  { id: 207, kanji: '災害', reading: 'さいがい', meaning: 'Kecelakaan' },
  // === KOSAKATA TAMBAHAN ===
  // Keamanan & Higienitas Dasar
  { id: 208, kanji: '安全', reading: 'あんぜん', meaning: 'Keamanan' },
  { id: 209, kanji: 'HACCP', reading: 'ハサップ', meaning: 'HACCP' },
  { id: 210, kanji: '一般的衛生管理', reading: 'いっぱんてきえいせいかんり', meaning: 'Manajemen higienitas umum' },
  { id: 211, kanji: '手洗い', reading: 'てあらい', meaning: 'Cuci tangan' },
  { id: 212, kanji: '消毒', reading: 'しょうどく', meaning: 'Disinfeksi' },
  { id: 213, kanji: 'ウイルス', reading: 'ウイルス', meaning: 'Virus' },
  { id: 214, kanji: '汚染', reading: 'おせん', meaning: 'Kontaminasi' },
  { id: 215, kanji: '異物', reading: 'いぶつ', meaning: 'Benda asing' },
  { id: 216, kanji: '混入', reading: 'こんにゅう', meaning: 'Tercampur' },
  { id: 217, kanji: '温度管理', reading: 'おんどかんり', meaning: 'Manajemen suhu' },
  { id: 218, kanji: '冷蔵', reading: 'れいぞう', meaning: 'Pendinginan' },
  { id: 219, kanji: '冷凍', reading: 'れいとう', meaning: 'Pembekuan' },
  { id: 220, kanji: '加熱', reading: 'かねつ', meaning: 'Pemanasan' },
  { id: 221, kanji: '中心温度', reading: 'ちゅうしんおんど', meaning: 'Suhu tengah' },
  { id: 222, kanji: '記録', reading: 'きろく', meaning: 'Catatan' },
  { id: 223, kanji: '点検', reading: 'てんけん', meaning: 'Pengecekan' },
  { id: 224, kanji: '確認', reading: 'かくにん', meaning: 'Konfirmasi' },
  { id: 225, kanji: '不潔', reading: 'ふけつ', meaning: 'Kotor' },
  { id: 226, kanji: '作業着', reading: 'さぎょうぎ', meaning: 'Pakaian kerja' },
  { id: 227, kanji: 'マスク', reading: 'マスク', meaning: 'Masker' },
  { id: 228, kanji: '手袋', reading: 'てぶくろ', meaning: 'Sarung tangan' },
  { id: 229, kanji: '長靴', reading: 'ながぐつ', meaning: 'Sepatu boot' },
  { id: 230, kanji: 'エプロン', reading: 'エプロン', meaning: 'Celemek' },
  { id: 231, kanji: '着用', reading: 'ちゃくよう', meaning: 'Mengenakan' },
  { id: 232, kanji: '健康', reading: 'けんこう', meaning: 'Kesehatan' },
  { id: 233, kanji: '怪我', reading: 'けが', meaning: 'Luka' },
  { id: 234, kanji: '絆創膏', reading: 'ばんそうこう', meaning: 'Plester' },
  { id: 235, kanji: '報告', reading: 'ほうこく', meaning: 'Laporan' },
  { id: 236, kanji: '徹底', reading: 'てってい', meaning: 'Menyeluruh' },
  { id: 237, kanji: 'ルール', reading: 'ルール', meaning: 'Aturan' },
  { id: 238, kanji: '守る', reading: 'まもる', meaning: 'Mematuhi' },
  { id: 239, kanji: '区域', reading: 'くいき', meaning: 'Zona' },
  { id: 240, kanji: '清潔区域', reading: 'せいけつくいき', meaning: 'Zona bersih' },
  { id: 241, kanji: '汚染区域', reading: 'おせんくいき', meaning: 'Zona kotor' },
  { id: 242, kanji: '床', reading: 'ゆか', meaning: 'Lantai' },
  { id: 243, kanji: '壁', reading: 'かべ', meaning: 'Dinding' },
  { id: 244, kanji: '天井', reading: 'てんじょう', meaning: 'Langit-langit' },
  { id: 245, kanji: '排水溝', reading: 'はいすいこう', meaning: 'Pembuangan air' },
  { id: 246, kanji: '換気', reading: 'かんき', meaning: 'Ventilasi' },
  { id: 247, kanji: '害虫', reading: 'がいちゅう', meaning: 'Hama' },
  { id: 248, kanji: '駆除', reading: 'くじょ', meaning: 'Pembasmian' },
  { id: 249, kanji: 'ネズミ', reading: 'ネズミ', meaning: 'Tikus' },
  { id: 250, kanji: 'ゴキブリ', reading: 'ゴキブリ', meaning: 'Kecoa' },
  { id: 251, kanji: 'ハエ', reading: 'ハエ', meaning: 'Lalat' },
  { id: 252, kanji: '防虫', reading: 'ぼうちゅう', meaning: 'Anti serangga' },
  { id: 253, kanji: '標準化', reading: 'ひょうじゅんか', meaning: 'Standarisasi' },
  { id: 254, kanji: '掃除', reading: 'そうじ', meaning: 'Bersih-bersih' },
  { id: 255, kanji: '5S', reading: 'ごえす', meaning: '5S' },
  { id: 256, kanji: '定位置', reading: 'ていいち', meaning: 'Posisi tetap' },
  { id: 257, kanji: '躾', reading: 'しつけ', meaning: 'Disiplin' },
  { id: 258, kanji: '洗剤', reading: 'せんざい', meaning: 'Deterjen' },
  { id: 259, kanji: '漂白剤', reading: 'ひょうはくざい', meaning: 'Pemutih' },
  { id: 260, kanji: 'アルコール', reading: 'アルコール', meaning: 'Alkohol' },
  { id: 261, kanji: '濃度', reading: 'のうど', meaning: 'Kadar/Konsentrasi' },
  { id: 262, kanji: '蛇口', reading: 'じゃぐち', meaning: 'Keran' },
  { id: 263, kanji: '水道水', reading: 'すいどうすい', meaning: 'Air keran' },
  { id: 264, kanji: '飲料水', reading: 'いんりょうすい', meaning: 'Air minum' },
  { id: 265, kanji: '食品添加物', reading: 'しょくひんてんかぶつ', meaning: 'Aditif makanan' },
  { id: 266, kanji: 'アレルゲン', reading: 'アレルゲン', meaning: 'Alergen' },
  { id: 267, kanji: '小麦', reading: 'こむぎ', meaning: 'Gandum' },
  { id: 268, kanji: '卵', reading: 'たまご', meaning: 'Telur' },
  { id: 269, kanji: '牛乳', reading: 'ぎゅうにゅう', meaning: 'Susu sapi' },
  { id: 270, kanji: '乳製品', reading: 'にゅうせいひん', meaning: 'Produk susu' },
  { id: 271, kanji: 'エビ', reading: 'エビ', meaning: 'Udang' },
  { id: 272, kanji: 'カニ', reading: 'カニ', meaning: 'Kepiting' },
  { id: 273, kanji: 'そば', reading: 'そば', meaning: 'Soba' },
  { id: 274, kanji: '賞味期限', reading: 'しょうみきげん', meaning: 'Best before' },
  { id: 275, kanji: '消費期限', reading: 'しょうひきげん', meaning: 'Use by' },
  { id: 276, kanji: '保存', reading: 'ほぞん', meaning: 'Penyimpanan' },
  { id: 277, kanji: '保存方法', reading: 'ほぞんほうほう', meaning: 'Metode penyimpanan' },
  { id: 278, kanji: '仕入れ', reading: 'しいれ', meaning: 'Pembelian bahan' },
  { id: 279, kanji: '受け入れ', reading: 'うけいれ', meaning: 'Penerimaan barang' },
  { id: 280, kanji: '金属探知機', reading: 'きんぞくたんちき', meaning: 'Detektor logam' },
  { id: 281, kanji: '抜き取り検査', reading: 'ぬきとりけんさ', meaning: 'Pemeriksaan sampel' },
  // Keselamatan Kerja Tambahan
  { id: 282, kanji: '事故', reading: 'じこ', meaning: 'Kecelakaan' },
  { id: 283, kanji: '安全第一', reading: 'あんぜんだいいち', meaning: 'Keselamatan adalah yang utama' },
  { id: 284, kanji: 'ヘルメット', reading: 'ヘルメット', meaning: 'Helm' },
  { id: 285, kanji: '安全帯', reading: 'あんぜんたい', meaning: 'Sabuk pengaman' },
  { id: 286, kanji: '耳栓', reading: 'みみせん', meaning: 'Penyumbat telinga' },
  { id: 287, kanji: '防護服', reading: 'ぼうごふく', meaning: 'Pakaian pelindung' },
  { id: 288, kanji: '注意', reading: 'ちゅうい', meaning: 'Perhatian' },
  { id: 289, kanji: '警告', reading: 'けいこく', meaning: 'Peringatan' },
  { id: 290, kanji: '標識', reading: 'ひょうしき', meaning: 'Rambu' },
  { id: 291, kanji: '禁止', reading: 'きんし', meaning: 'Dilarang' },
  { id: 292, kanji: '立入禁止', reading: 'たちいりきんし', meaning: 'Dilarang masuk' },
  { id: 293, kanji: '危険物', reading: 'きけんぶつ', meaning: 'Benda berbahaya' },
  { id: 294, kanji: '火気厳禁', reading: 'かきげんきん', meaning: 'Dilarang api' },
  { id: 295, kanji: 'スイッチ', reading: 'スイッチ', meaning: 'Saklar' },
  { id: 296, kanji: '操作', reading: 'そうさ', meaning: 'Operasi' },
  { id: 297, kanji: '非常停止', reading: 'ひじょうていし', meaning: 'Emergency stop' },
  { id: 298, kanji: 'カバー', reading: 'カバー', meaning: 'Penutup mesin' },
  { id: 299, kanji: '挟まれ', reading: 'はさまれ', meaning: 'Terjepit' },
  { id: 300, kanji: '巻き込まれ', reading: 'まきこまれ', meaning: 'Tergulung' },
  { id: 301, kanji: '滑る', reading: 'すべる', meaning: 'Tergelincir' },
  { id: 302, kanji: '墜落', reading: 'ついらく', meaning: 'Jatuh dari ketinggian' },
  { id: 303, kanji: '感電', reading: 'かんでん', meaning: 'Kesetrum' },
  { id: 304, kanji: '火傷', reading: 'やけど', meaning: 'Luka bakar' },
  { id: 305, kanji: '切れ', reading: 'きれ', meaning: 'Terpotong' },
  { id: 306, kanji: '刺され', reading: 'さされ', meaning: 'Tertusuk' },
  { id: 307, kanji: '運ぶ', reading: 'はこぶ', meaning: 'Mengangkut' },
  { id: 308, kanji: '持ち上げる', reading: 'もちあげる', meaning: 'Mengangkat' },
  { id: 309, kanji: 'フォークリフト', reading: 'フォークリフト', meaning: 'Forklift' },
  { id: 310, kanji: '始業前点検', reading: 'しぎょうまえてんけん', meaning: 'Pengecekan awal' },
  { id: 311, kanji: '終業後点検', reading: 'しゅうぎょうごてんけん', meaning: 'Pengecekan akhir' },
  { id: 312, kanji: '故障', reading: 'こしょう', meaning: 'Rusak' },
  { id: 313, kanji: '修理', reading: 'しゅうり', meaning: 'Perbaikan' },
  { id: 314, kanji: '連絡', reading: 'れんらく', meaning: 'Kontak' },
  { id: 315, kanji: '相談', reading: 'そうだん', meaning: 'Diskusi' },
  { id: 316, kanji: '報連相', reading: 'ほうれんそう', meaning: 'Horenso (Lapor-Konsultasi-Berbagi)' },
  { id: 317, kanji: 'リーダー', reading: 'リーダー', meaning: 'Pemimpin' },
  { id: 318, kanji: '避難', reading: 'ひなん', meaning: 'Evakuasi' },
  { id: 319, kanji: '避難経路', reading: 'ひなんけいろ', meaning: 'Rute evakuasi' },
  { id: 320, kanji: '非常口', reading: 'ひじょうぐち', meaning: 'Pintu darurat' },
  { id: 321, kanji: '消化器', reading: 'しょうかき', meaning: 'APAR' },
  { id: 322, kanji: '地震', reading: 'じしん', meaning: 'Gempa' },
  { id: 323, kanji: '救急箱', reading: 'きゅうきゅうばこ', meaning: 'Kotak P3K' },
  { id: 324, kanji: '応急手当', reading: 'おうきゅうてあて', meaning: 'Pertolongan pertama' },
  { id: 325, kanji: 'AED', reading: 'エーイーディー', meaning: 'AED' },
  { id: 326, kanji: '確保', reading: 'かくほ', meaning: 'Mengamankan' },
  { id: 327, kanji: '注意喚起', reading: 'ちゅういかんき', meaning: 'Imbauan' },
  { id: 328, kanji: 'KYT', reading: 'ケーワイティー', meaning: 'KYT' },
  { id: 329, kanji: 'ヒヤリハット', reading: 'ヒヤリハット', meaning: 'Near-miss' },
  { id: 330, kanji: '危険予知', reading: 'きけんよち', meaning: 'Prediksi bahaya' },
  { id: 331, kanji: 'ミーティング', reading: 'ミーティング', meaning: 'Rapat' },
  { id: 332, kanji: '朝礼', reading: 'ちょうれい', meaning: 'Apel pagi' },
  { id: 333, kanji: '体操', reading: 'たいそう', meaning: 'Senam' },
  { id: 334, kanji: '化学薬品', reading: 'かがくやくひん', meaning: 'Bahan kimia' },
  { id: 335, kanji: '有害', reading: 'ゆうがい', meaning: 'Berbahaya' },
  { id: 336, kanji: '物質', reading: 'ぶっしつ', meaning: 'Zat/Bahan' },
  { id: 337, kanji: 'SDS', reading: 'エスディーエス', meaning: 'SDS' },
  { id: 338, kanji: '漏れる', reading: 'もれる', meaning: 'Bocor' },
  { id: 339, kanji: '騒音', reading: 'そうおん', meaning: 'Bising' },
  { id: 340, kanji: '粉塵', reading: 'ふんじん', meaning: 'Debu berbahaya' },
  { id: 341, kanji: '酸欠', reading: 'さんけつ', meaning: 'Kekurangan oksigen' },
  { id: 342, kanji: '多湿', reading: 'たしつ', meaning: 'Lembab' },
  { id: 343, kanji: '照明', reading: 'しょうめい', meaning: 'Penerangan' },
  { id: 344, kanji: '暗い', reading: 'くらい', meaning: 'Gelap' },
  { id: 345, kanji: '明るい', reading: 'あかるい', meaning: 'Terang' },
  { id: 346, kanji: '疲労', reading: 'ひろう', meaning: 'Kelelahan' },
  { id: 347, kanji: '休憩', reading: 'きゅうけい', meaning: 'Istirahat' },
  { id: 348, kanji: '睡眠', reading: 'すいみん', meaning: 'Tidur' },
  { id: 349, kanji: 'ストレス', reading: 'ストレス', meaning: 'Stres' },
  { id: 350, kanji: '健康診断', reading: 'けんこうしんだん', meaning: 'Medical check up' },
  { id: 351, kanji: '手順', reading: 'てじゅん', meaning: 'Prosedur' },
  { id: 352, kanji: '手順書', reading: 'てじゅんしょ', meaning: 'SOP' },
  { id: 353, kanji: '担当者', reading: 'たんとうしゃ', meaning: 'Petugas' },
  { id: 354, kanji: '作業', reading: 'さぎょう', meaning: 'Operasi kerja' },
  { id: 355, kanji: '環境', reading: 'かんきょう', meaning: 'Lingkungan' },
  { id: 356, kanji: '改善', reading: 'かいぜん', meaning: 'Perbaikan/Kaizen' },
  // Mesin & Alat
  { id: 357, kanji: 'コンベア', reading: 'コンベア', meaning: 'Conveyor' },
  { id: 358, kanji: '充填機', reading: 'じゅうてんき', meaning: 'Mesin pengisi' },
  { id: 359, kanji: '包装機', reading: 'ほうそうき', meaning: 'Mesin pengemas' },
  { id: 360, kanji: '真空包装機', reading: 'しんくうほうそうき', meaning: 'Pengemas vakum' },
  { id: 361, kanji: 'ラベラー', reading: 'ラベラー', meaning: 'Mesin pelabel' },
  { id: 362, kanji: 'シーラー', reading: 'シーラー', meaning: 'Mesin segel' },
  { id: 363, kanji: 'カッター', reading: 'カッター', meaning: 'Mesin pemotong' },
  { id: 364, kanji: 'スライサー', reading: 'スライサー', meaning: 'Mesin pengiris' },
  { id: 365, kanji: 'ミキサー', reading: 'ミキサー', meaning: 'Mixer' },
  { id: 366, kanji: '撹拌機', reading: 'かくはんき', meaning: 'Agitator' },
  { id: 367, kanji: '粉砕機', reading: 'ふんさいき', meaning: 'Penggiling' },
  { id: 368, kanji: '成形機', reading: 'せいけいき', meaning: 'Mesin pencetak' },
  { id: 369, kanji: '急速冷凍機', reading: 'きゅうそくれいとうき', meaning: 'Blast freezer' },
  { id: 370, kanji: '解凍機', reading: 'かいとうき', meaning: 'Defroster' },
  { id: 371, kanji: '殺菌機', reading: 'さっきんき', meaning: 'Mesin sterilisasi' },
  { id: 372, kanji: '釜', reading: 'かま', meaning: 'Ketel besar' },
  { id: 373, kanji: 'ボイラー', reading: 'ボイラー', meaning: 'Boiler' },
  { id: 374, kanji: '蒸し器', reading: 'むしき', meaning: 'Steamer' },
  { id: 375, kanji: 'フライヤー', reading: 'フライヤー', meaning: 'Fryer' },
  { id: 376, kanji: 'オーブン', reading: 'オーブン', meaning: 'Oven' },
  { id: 377, kanji: '乾燥機', reading: 'かんそうき', meaning: 'Mesin pengering' },
  { id: 378, kanji: '洗浄機', reading: 'せんじょうき', meaning: 'Mesin pencuci' },
  { id: 379, kanji: '異物除去機', reading: 'いぶつじょきょき', meaning: 'Penghilang benda asing' },
  { id: 380, kanji: 'X線検査機', reading: 'エックスせんけんさき', meaning: 'X-ray inspector' },
  { id: 381, kanji: '重量計', reading: 'じゅうりょうけい', meaning: 'Timbangan' },
  { id: 382, kanji: '秤', reading: 'はかり', meaning: 'Timbangan kecil' },
  { id: 383, kanji: '選別機', reading: 'せんべつき', meaning: 'Mesin sortasi' },
  { id: 384, kanji: 'タンク', reading: 'タンク', meaning: 'Tangki' },
  { id: 385, kanji: 'ポンプ', reading: 'ポンプ', meaning: 'Pompa' },
  { id: 386, kanji: 'バルブ', reading: 'バルブ', meaning: 'Valve' },
  { id: 387, kanji: '配管', reading: 'はいかん', meaning: 'Pipa' },
  { id: 388, kanji: 'ホース', reading: 'ホース', meaning: 'Selang' },
  { id: 389, kanji: 'まな板', reading: 'まないた', meaning: 'Talenan' },
  { id: 390, kanji: 'ザル', reading: 'ザル', meaning: 'Saringan' },
  { id: 391, kanji: 'ボウル', reading: 'ボウル', meaning: 'Mangkuk' },
  { id: 392, kanji: 'コンテナ', reading: 'コンテナ', meaning: 'Kontainer' },
  { id: 393, kanji: 'パレット', reading: 'パレット', meaning: 'Palet' },
  { id: 394, kanji: 'バット', reading: 'バット', meaning: 'Nampan' },
  { id: 395, kanji: '温度計', reading: 'おんどけい', meaning: 'Termometer' },
  { id: 396, kanji: 'モーター', reading: 'モーター', meaning: 'Motor' },
  { id: 397, kanji: 'ベルト', reading: 'ベルト', meaning: 'Belt conveyor' },
  { id: 398, kanji: 'チェーン', reading: 'チェーン', meaning: 'Rantai' },
  { id: 399, kanji: 'フィルター', reading: 'フィルター', meaning: 'Filter' },
  { id: 400, kanji: 'センサー', reading: 'センサー', meaning: 'Sensor' },
  { id: 401, kanji: 'パネル', reading: 'パネル', meaning: 'Panel kontrol' },
  { id: 402, kanji: 'ボタン', reading: 'ボタン', meaning: 'Tombol' },
  { id: 403, kanji: 'レバー', reading: 'レバー', meaning: 'Tuas' },
  { id: 404, kanji: 'ハンドル', reading: 'ハンドル', meaning: 'Pegangan' },
  { id: 405, kanji: '備品', reading: 'びひん', meaning: 'Perlengkapan' },
  { id: 406, kanji: '部品', reading: 'ぶひん', meaning: 'Suku cadang' },
  { id: 407, kanji: '潤滑油', reading: 'じゅんかつゆ', meaning: 'Minyak pelumas' },
  { id: 408, kanji: 'ブラシ', reading: 'ブラシ', meaning: 'Sikat' },
  { id: 409, kanji: 'モップ', reading: 'モップ', meaning: 'Pel' },
  { id: 410, kanji: 'バケツ', reading: 'バケツ', meaning: 'Ember' },
  { id: 411, kanji: '雑巾', reading: 'ぞうきん', meaning: 'Kain lap' },
  { id: 412, kanji: 'スポンジ', reading: 'スポンジ', meaning: 'Spons' },
  { id: 413, kanji: 'ゴミ箱', reading: 'ごみばこ', meaning: 'Tempat sampah' },
  { id: 414, kanji: '廃棄物', reading: 'はいきぶつ', meaning: 'Limbah' },
  { id: 415, kanji: 'ボルト', reading: 'ボルト', meaning: 'Baut' },
  { id: 416, kanji: 'ナット', reading: 'ナット', meaning: 'Mur' },
  { id: 417, kanji: 'ネジ', reading: 'ネジ', meaning: 'Sekrup' },
  { id: 418, kanji: 'ドライバー', reading: 'ドライバー', meaning: 'Obeng' },
  { id: 419, kanji: 'ハンマー', reading: 'ハンマー', meaning: 'Palu' },
  // Bahan & Produk
  { id: 420, kanji: '原料', reading: 'げんりょう', meaning: 'Bahan mentah' },
  { id: 421, kanji: '材料', reading: 'ざいりょう', meaning: 'Material' },
  { id: 422, kanji: '半製品', reading: 'はんせいひん', meaning: 'Produk setengah jadi' },
  { id: 423, kanji: '不良品', reading: 'ふりょうひん', meaning: 'Produk cacat' },
  { id: 424, kanji: '良品', reading: 'りょうひん', meaning: 'Produk bagus' },
  { id: 425, kanji: 'サンプル', reading: 'サンプル', meaning: 'Sampel' },
  { id: 426, kanji: '在庫', reading: 'ざいこ', meaning: 'Stok' },
  { id: 427, kanji: '入荷', reading: 'にゅうか', meaning: 'Penerimaan barang' },
  { id: 428, kanji: '倉庫', reading: 'そうこ', meaning: 'Gudang' },
  { id: 429, kanji: '冷凍倉庫', reading: 'れいとうそうこ', meaning: 'Cold storage' },
  { id: 430, kanji: '段ボール', reading: 'だんボール', meaning: 'Kardus' },
  { id: 431, kanji: '袋', reading: 'ふくろ', meaning: 'Kantong' },
  { id: 432, kanji: '瓶', reading: 'びん', meaning: 'Botol kaca' },
  { id: 433, kanji: '缶', reading: 'かん', meaning: 'Kaleng' },
  { id: 434, kanji: 'ペットボトル', reading: 'ペットボトル', meaning: 'Botol plastik' },
  { id: 435, kanji: 'ラベル', reading: 'ラベル', meaning: 'Label' },
  { id: 436, kanji: 'シール', reading: 'シール', meaning: 'Stiker' },
  { id: 437, kanji: '蓋', reading: 'ふた', meaning: 'Tutup' },
  { id: 438, kanji: '水', reading: 'みず', meaning: 'Air' },
  { id: 439, kanji: 'お湯', reading: 'おゆ', meaning: 'Air panas' },
  { id: 440, kanji: '氷', reading: 'こおり', meaning: 'Es' },
  { id: 441, kanji: '蒸気', reading: 'じょうき', meaning: 'Uap' },
  { id: 442, kanji: '空気', reading: 'くうき', meaning: 'Udara' },
  { id: 443, kanji: '棚', reading: 'たな', meaning: 'Rak' },
  { id: 444, kanji: '先入れ先出し', reading: 'さきいれさきだし', meaning: 'FIFO' },
  { id: 445, kanji: 'ロット番号', reading: 'ロットばんごう', meaning: 'Lot number' },
  { id: 446, kanji: '製造年月日', reading: 'せいぞうねんがっぴ', meaning: 'Tanggal produksi' },
  { id: 447, kanji: '栄養成分', reading: 'えいようせいぶん', meaning: 'Kandungan nutrisi' },
  { id: 448, kanji: 'カロリー', reading: 'カロリー', meaning: 'Kalori' },
  { id: 449, kanji: 'たんぱく質', reading: 'たんぱくしつ', meaning: 'Protein' },
  { id: 450, kanji: '脂質', reading: 'ししつ', meaning: 'Lemak (kandungan)' },
  { id: 451, kanji: '炭水化物', reading: 'たんすいかぶつ', meaning: 'Karbohidrat' },
  { id: 452, kanji: 'ナトリウム', reading: 'ナトリウム', meaning: 'Sodium' },
  { id: 453, kanji: 'バーコード', reading: 'バーコード', meaning: 'Barcode' },
  // Kata Kerja Produksi
  { id: 454, kanji: '起動する', reading: 'きどうする', meaning: 'Start up' },
  { id: 455, kanji: '調整する', reading: 'ちょうせいする', meaning: 'Menyesuaikan' },
  { id: 456, kanji: '設定する', reading: 'せっていする', meaning: 'Setting' },
  { id: 457, kanji: '交換する', reading: 'こうかんする', meaning: 'Mengganti' },
  { id: 458, kanji: '補充する', reading: 'ほじゅうする', meaning: 'Refill' },
  { id: 459, kanji: '片付ける', reading: 'かたづける', meaning: 'Merapikan' },
  { id: 460, kanji: '並べる', reading: 'ならべる', meaning: 'Menyusun' },
  { id: 461, kanji: '積む', reading: 'つむ', meaning: 'Menumpuk' },
  { id: 462, kanji: '包装する', reading: 'ほうそうする', meaning: 'Mengemas' },
  { id: 463, kanji: '詰める', reading: 'つめる', meaning: 'Mengisi kemasan' },
  { id: 464, kanji: '包む', reading: 'つつむ', meaning: 'Membungkus' },
  { id: 465, kanji: '貼る', reading: 'はる', meaning: 'Menempel label' },
  { id: 466, kanji: '印刷する', reading: 'いんさつする', meaning: 'Mencetak' },
  { id: 467, kanji: '印字する', reading: 'いんじする', meaning: 'Cetak tanggal' },
  { id: 468, kanji: '封をする', reading: 'ふうをする', meaning: 'Menyegel' },
  { id: 469, kanji: '開ける', reading: 'あける', meaning: 'Membuka' },
  { id: 470, kanji: '閉める', reading: 'しめる', meaning: 'Menutup' },
  { id: 471, kanji: '運搬する', reading: 'うんぱんする', meaning: 'Mengangkut' },
  { id: 472, kanji: '保管する', reading: 'ほかんする', meaning: 'Menyimpan' },
  { id: 473, kanji: '置く', reading: 'おく', meaning: 'Meletakkan' },
  { id: 474, kanji: '捨てる', reading: 'すてる', meaning: 'Membuang' },
  { id: 475, kanji: '廃棄する', reading: 'はいきする', meaning: 'Membuang limbah' },
  { id: 476, kanji: '掃除する', reading: 'そうじする', meaning: 'Membersihkan' },
  { id: 477, kanji: '拭く', reading: 'ふく', meaning: 'Mengelap' },
  { id: 478, kanji: '磨く', reading: 'みがく', meaning: 'Memoles' },
  { id: 479, kanji: '乾かす', reading: 'かわかす', meaning: 'Mengeringkan' },
  { id: 480, kanji: '修理する', reading: 'しゅうりする', meaning: 'Memperbaiki' },
  { id: 481, kanji: '製造する', reading: 'せいぞうする', meaning: 'Memproduksi' },
  { id: 482, kanji: '作る', reading: 'つくる', meaning: 'Membuat' },
  { id: 483, kanji: '加工する', reading: 'かこうする', meaning: 'Memproses' },
  { id: 484, kanji: '殺菌する', reading: 'さっきんする', meaning: 'Mensterilkan' },
  { id: 485, kanji: '準備する', reading: 'じゅんびする', meaning: 'Menyiapkan' },
  { id: 486, kanji: '始める', reading: 'はじめる', meaning: 'Memulai' },
  { id: 487, kanji: '終わる', reading: 'おわる', meaning: 'Selesai' },
  { id: 488, kanji: '完了する', reading: 'かんりょうする', meaning: 'Tuntas' },
  { id: 489, kanji: '管理する', reading: 'かんりする', meaning: 'Mengelola' },
  // Kualitas
  { id: 490, kanji: '品質管理', reading: 'ひんしつかんり', meaning: 'Kontrol kualitas' },
  { id: 491, kanji: '不具合', reading: 'ふぐあい', meaning: 'Ketidaksesuaian' },
  { id: 492, kanji: '規格', reading: 'きかく', meaning: 'Standar produk' },
  { id: 493, kanji: '規格外', reading: 'きかくがい', meaning: 'Non-standar' },
  { id: 494, kanji: '合格', reading: 'ごうかく', meaning: 'Lulus' },
  { id: 495, kanji: '不合格', reading: 'ふごうかく', meaning: 'Tidak lulus' },
  { id: 496, kanji: 'クレーム', reading: 'クレーム', meaning: 'Komplain' },
  { id: 497, kanji: '苦情', reading: 'くじょう', meaning: 'Keluhan' },
  { id: 498, kanji: '回収', reading: 'かいしゅう', meaning: 'Recall' },
  { id: 499, kanji: '対策', reading: 'たいさく', meaning: 'Tindakan' },
  { id: 500, kanji: '再発防止', reading: 'さいはつぼうし', meaning: 'Pencegahan ulang' },
  { id: 501, kanji: '色', reading: 'いろ', meaning: 'Warna' },
  { id: 502, kanji: '形', reading: 'かたち', meaning: 'Bentuk' },
  { id: 503, kanji: '匂い', reading: 'におい', meaning: 'Aroma' },
  { id: 504, kanji: '味', reading: 'あじ', meaning: 'Rasa' },
  { id: 505, kanji: '食感', reading: 'しょっかん', meaning: 'Tekstur' },
  { id: 506, kanji: '異味', reading: 'いみ', meaning: 'Rasa aneh' },
  { id: 507, kanji: '異臭', reading: 'いしゅう', meaning: 'Bau aneh' },
  { id: 508, kanji: '破損', reading: 'はそん', meaning: 'Kerusakan' },
  { id: 509, kanji: '傷', reading: 'きず', meaning: 'Luka/gores' },
  { id: 510, kanji: '汚れ', reading: 'よごれ', meaning: 'Kotoran' },
  { id: 511, kanji: '虫', reading: 'むし', meaning: 'Serangga' },
  { id: 512, kanji: 'プラスチック片', reading: 'プラスチックへん', meaning: 'Pecahan plastik' },
  { id: 513, kanji: 'ガラス片', reading: 'ガラスへん', meaning: 'Pecahan kaca' },
  { id: 514, kanji: '金属片', reading: 'きんぞくへん', meaning: 'Pecahan logam' },
  { id: 515, kanji: 'カビ', reading: 'カビ', meaning: 'Jamur' },
  { id: 516, kanji: '腐敗', reading: 'ふはい', meaning: 'Pembusukan' },
  { id: 517, kanji: '鮮度', reading: 'せんど', meaning: 'Kesegaran' },
  { id: 518, kanji: '酸化', reading: 'さんか', meaning: 'Oksidasi' },
  { id: 519, kanji: '変色', reading: 'へんしょく', meaning: 'Perubahan warna' },
  { id: 520, kanji: '目視検査', reading: 'もくしけんさ', meaning: 'Inspeksi visual' },
  { id: 521, kanji: '官能検査', reading: 'かんのうけんさ', meaning: 'Tes organoleptik' },
  { id: 522, kanji: '一般生菌数', reading: 'いっぱんせいきんすう', meaning: 'Jumlah bakteri umum' },
  { id: 523, kanji: '大腸菌', reading: 'だいちょうきん', meaning: 'E.coli' },
  { id: 524, kanji: 'サルモネラ菌', reading: 'サルモネラきん', meaning: 'Salmonella' },
  { id: 525, kanji: '拭き取り検査', reading: 'ふきとりけんさ', meaning: 'Swab test' },
  // Sifat & Kondisi Makanan
  { id: 526, kanji: '新鮮', reading: 'しんせん', meaning: 'Segar' },
  { id: 527, kanji: '固い', reading: 'かたい', meaning: 'Keras' },
  { id: 528, kanji: '柔らかい', reading: 'やわらかい', meaning: 'Lunak' },
  { id: 529, kanji: '熱い', reading: 'あつい', meaning: 'Panas' },
  { id: 530, kanji: '冷たい', reading: 'つめたい', meaning: 'Dingin' },
  { id: 531, kanji: '温い', reading: 'ぬるい', meaning: 'Hangat' },
  { id: 532, kanji: '濃い', reading: 'こい', meaning: 'Pekat' },
  { id: 533, kanji: '薄い', reading: 'うすい', meaning: 'Encer' },
  { id: 534, kanji: '甘い', reading: 'あまい', meaning: 'Manis' },
  { id: 535, kanji: '辛い', reading: 'からい', meaning: 'Pedas' },
  { id: 536, kanji: '塩辛い', reading: 'しおからい', meaning: 'Asin' },
  { id: 537, kanji: '酸っぱい', reading: 'すっぱい', meaning: 'Asam' },
  { id: 538, kanji: '苦い', reading: 'にがい', meaning: 'Pahit' },
  { id: 539, kanji: '美味しい', reading: 'おいしい', meaning: 'Enak' },
  { id: 540, kanji: '不味い', reading: 'まずい', meaning: 'Tidak enak' },
  { id: 541, kanji: '臭い', reading: 'くさい', meaning: 'Bau busuk' },
  { id: 542, kanji: '正常', reading: 'せいじょう', meaning: 'Normal' },
  { id: 543, kanji: '適切', reading: 'てきせつ', meaning: 'Sesuai' },
  { id: 544, kanji: '不適切', reading: 'ふてきせつ', meaning: 'Tidak sesuai' },
  { id: 545, kanji: 'ベトベト', reading: 'ベトベト', meaning: 'Lengket' },
  { id: 546, kanji: 'ネバネバ', reading: 'ネバネバ', meaning: 'Berlendir' },
  { id: 547, kanji: 'サラサラ', reading: 'サラサラ', meaning: 'Kering halus' },
  { id: 548, kanji: 'ドロドロ', reading: 'ドロドロ', meaning: 'Kental cair' },
  { id: 549, kanji: 'カチカチ', reading: 'カチカチ', meaning: 'Keras sekali' },
  { id: 550, kanji: 'フワフワ', reading: 'フワフワ', meaning: 'Lembut ringan' },
  { id: 551, kanji: 'カリカリ', reading: 'カリカリ', meaning: 'Renyah keras' },
  { id: 552, kanji: 'サクサク', reading: 'サクサク', meaning: 'Renyah ringan' },
  { id: 553, kanji: 'モチモチ', reading: 'モチモチ', meaning: 'Kenyal' },
  // Bahan Makanan
  { id: 554, kanji: '肉', reading: 'にく', meaning: 'Daging' },
  { id: 555, kanji: '豚肉', reading: 'ぶたにく', meaning: 'Daging babi' },
  { id: 556, kanji: '牛肉', reading: 'ぎゅうにく', meaning: 'Daging sapi' },
  { id: 557, kanji: '鶏肉', reading: 'とりにく', meaning: 'Daging ayam' },
  { id: 558, kanji: '魚', reading: 'さかな', meaning: 'Ikan' },
  { id: 559, kanji: '野菜', reading: 'やさい', meaning: 'Sayur' },
  { id: 560, kanji: '果物', reading: 'くだもの', meaning: 'Buah' },
  { id: 561, kanji: '米', reading: 'こめ', meaning: 'Beras' },
  { id: 562, kanji: '小麦粉', reading: 'こむぎこ', meaning: 'Tepung terigu' },
  { id: 563, kanji: '片栗粉', reading: 'かたくりこ', meaning: 'Maizena' },
  { id: 564, kanji: 'パン粉', reading: 'パンこ', meaning: 'Tepung roti' },
  { id: 565, kanji: '生地', reading: 'きじ', meaning: 'Adonan' },
  { id: 566, kanji: '玉ねぎ', reading: 'たまねぎ', meaning: 'Bawang' },
  { id: 567, kanji: '人参', reading: 'にんじん', meaning: 'Wortel' },
  { id: 568, kanji: 'じゃが芋', reading: 'じゃがいも', meaning: 'Kentang' },
  { id: 569, kanji: 'キャベツ', reading: 'キャベツ', meaning: 'Kubis' },
  { id: 570, kanji: '大根', reading: 'だいこん', meaning: 'Lobak' },
  { id: 571, kanji: 'もやし', reading: 'もやし', meaning: 'Tauge' },
  { id: 572, kanji: '茸', reading: 'きのこ', meaning: 'Jamur' },
  { id: 573, kanji: '鮭', reading: 'さけ', meaning: 'Ikan salmon' },
  { id: 574, kanji: '鮪', reading: 'まぐろ', meaning: 'Ikan tuna' },
  { id: 575, kanji: '鯖', reading: 'さば', meaning: 'Ikan kembung' },
  { id: 576, kanji: '烏賊', reading: 'いか', meaning: 'Cumi' },
  { id: 577, kanji: '蛸', reading: 'たこ', meaning: 'Gurita' },
  { id: 578, kanji: '貝', reading: 'かい', meaning: 'Kerang' },
  { id: 579, kanji: '骨', reading: 'ほね', meaning: 'Tulang' },
  { id: 580, kanji: '皮', reading: 'かわ', meaning: 'Kulit' },
  { id: 581, kanji: '脂肪', reading: 'しぼう', meaning: 'Lemak' },
  { id: 582, kanji: '赤身', reading: 'あかみ', meaning: 'Daging merah' },
  { id: 583, kanji: '白身', reading: 'しろみ', meaning: 'Daging putih/ikan putih' },
  // Kemasan & Logistik
  { id: 584, kanji: 'トレー', reading: 'トレー', meaning: 'Baki' },
  { id: 585, kanji: 'フィルム', reading: 'フィルム', meaning: 'Film kemasan' },
  { id: 586, kanji: 'ラップ', reading: 'ラップ', meaning: 'Plastic wrap' },
  { id: 587, kanji: 'アルミホイル', reading: 'アルミホイル', meaning: 'Aluminium foil' },
  { id: 588, kanji: '梱包', reading: 'こんぽう', meaning: 'Packing' },
  { id: 589, kanji: '在庫管理', reading: 'ざいこかんり', meaning: 'Manajemen stok' },
  { id: 590, kanji: '棚卸', reading: 'たなおろし', meaning: 'Stock opname' },
  { id: 591, kanji: '発注', reading: 'はっちゅう', meaning: 'Pemesanan' },
  { id: 592, kanji: '納品', reading: 'のうひん', meaning: 'Pengiriman barang' },
  { id: 593, kanji: '返品', reading: 'へんぴん', meaning: 'Retur' },
  { id: 594, kanji: '荷物', reading: 'にもつ', meaning: 'Barang' },
  { id: 595, kanji: '天地無用', reading: 'てんちむよう', meaning: 'Jangan dibalik' },
  { id: 596, kanji: '取扱注意', reading: 'とりあつかいちゅうい', meaning: 'Hati-hati' },
  { id: 597, kanji: '割れ物', reading: 'われもの', meaning: 'Fragile' },
  { id: 598, kanji: '伝票', reading: 'でんぴょう', meaning: 'Slip' },
  { id: 599, kanji: '送り状', reading: 'おくりじょう', meaning: 'Resi' },
  { id: 600, kanji: '輸入', reading: 'ゆにゅう', meaning: 'Impor' },
  { id: 601, kanji: '輸出', reading: 'ゆしゅつ', meaning: 'Ekspor' },
  { id: 602, kanji: '顧客', reading: 'こきゃく', meaning: 'Pelanggan' },
  { id: 603, kanji: '取引先', reading: 'とりひきさき', meaning: 'Mitra bisnis' },
  // Proses Pengolahan
  { id: 604, kanji: '発酵', reading: 'はっこう', meaning: 'Fermentasi' },
  { id: 605, kanji: '熟成', reading: 'じゅくせい', meaning: 'Pematangan' },
  { id: 606, kanji: '燻製', reading: 'くんせい', meaning: 'Pengasapan' },
  { id: 607, kanji: '漬物', reading: 'つけもの', meaning: 'Acar' },
  { id: 608, kanji: '骨抜き', reading: 'ほねぬき', meaning: 'Fillet' },
  { id: 609, kanji: 'ミンチ', reading: 'ミンチ', meaning: 'Daging cincang' },
  { id: 610, kanji: 'すり身', reading: 'すりみ', meaning: 'Daging lumat' },
  { id: 611, kanji: '沸騰', reading: 'ふっとう', meaning: 'Mendidih' },
  { id: 612, kanji: '濾過', reading: 'ろか', meaning: 'Filtrasi' },
  { id: 613, kanji: '攪拌', reading: 'かくはん', meaning: 'Pengadukan' },
  { id: 614, kanji: '抽出', reading: 'ちゅうしゅつ', meaning: 'Ekstraksi' },
  { id: 615, kanji: '配合', reading: 'はいごう', meaning: 'Pencampuran' },
  { id: 616, kanji: 'レシピ', reading: 'レシピ', meaning: 'Resep' },
  { id: 617, kanji: '割合', reading: 'わりあい', meaning: 'Proporsi' },
  { id: 618, kanji: '分量', reading: 'ぶんりょう', meaning: 'Takaran' },
  { id: 619, kanji: 'レトルト', reading: 'レトルト', meaning: 'Retort' },
  { id: 620, kanji: '滅菌', reading: 'めっきん', meaning: 'Sterilisasi' },
  { id: 621, kanji: '低温殺菌', reading: 'ていおんさっきん', meaning: 'Pasteurisasi' },
  { id: 622, kanji: '醸造', reading: 'じょうぞう', meaning: 'Brewing' },
  { id: 623, kanji: '酵母', reading: 'こうぼ', meaning: 'Ragi' },
  { id: 624, kanji: '麹', reading: 'こうじ', meaning: 'Koji' },
  { id: 625, kanji: '乳酸菌', reading: 'にゅうさんきん', meaning: 'Bakteri laktat' },
  { id: 626, kanji: 'フリーズドライ', reading: 'フリーズドライ', meaning: 'Freeze dry' },
  { id: 627, kanji: '充填', reading: 'じゅうてん', meaning: 'Pengisian' },
  { id: 628, kanji: '全数検査', reading: 'ぜんすうけんさ', meaning: 'Inspeksi 100%' },
  { id: 629, kanji: 'ロット', reading: 'ロット', meaning: 'Lot' },
  { id: 630, kanji: 'バッチ', reading: 'バッチ', meaning: 'Batch' },
  // Parameter Pengukuran
  { id: 631, kanji: 'pH', reading: 'ピーエイチ', meaning: 'pH' },
  { id: 632, kanji: '粘度', reading: 'ねんど', meaning: 'Viskositas' },
  { id: 633, kanji: '糖度', reading: 'とうど', meaning: 'Brix/Kadar gula' },
  { id: 634, kanji: '塩分', reading: 'えんぶん', meaning: 'Kadar garam' },
  { id: 635, kanji: '固形物', reading: 'こけいぶつ', meaning: 'Padatan' },
  { id: 636, kanji: '液体', reading: 'えきたい', meaning: 'Cair' },
  { id: 637, kanji: '粉末', reading: 'ふんまつ', meaning: 'Bubuk' },
  { id: 638, kanji: '顆粒', reading: 'かりゅう', meaning: 'Granul' },
  { id: 639, kanji: 'ペースト', reading: 'ペースト', meaning: 'Pasta' },
  { id: 640, kanji: '電圧', reading: 'でんあつ', meaning: 'Voltase' },
  { id: 641, kanji: '圧力', reading: 'あつりょく', meaning: 'Tekanan' },
  { id: 642, kanji: '速度', reading: 'そくど', meaning: 'Kecepatan' },
  { id: 643, kanji: '上限', reading: 'じょうげん', meaning: 'Batas atas' },
  { id: 644, kanji: '下限', reading: 'かげん', meaning: 'Batas bawah' },
  { id: 645, kanji: '許容範囲', reading: 'きょようはんい', meaning: 'Toleransi' },
  // Maintenance
  { id: 646, kanji: 'メンテナンス', reading: 'メンテナンス', meaning: 'Maintenance' },
  { id: 647, kanji: '定期点検', reading: 'ていきてんけん', meaning: 'Cek berkala' },
  { id: 648, kanji: '日常点検', reading: 'にちじょうてんけん', meaning: 'Cek harian' },
  { id: 649, kanji: '稼働', reading: 'かどう', meaning: 'Beroperasi' },
  { id: 650, kanji: '異常音', reading: 'いじょうおん', meaning: 'Suara abnormal' },
  { id: 651, kanji: '振動', reading: 'しんどう', meaning: 'Getaran' },
  { id: 652, kanji: '摩擦', reading: 'まさつ', meaning: 'Gesekan' },
  { id: 653, kanji: '摩耗', reading: 'まもう', meaning: 'Aus' },
  { id: 654, kanji: '緩み', reading: 'ゆるみ', meaning: 'Kendor' },
  { id: 655, kanji: '断線', reading: 'だんせん', meaning: 'Kabel putus' },
  { id: 656, kanji: 'ショート', reading: 'ショート', meaning: 'Korslet' },
  { id: 657, kanji: '警告灯', reading: 'けいこくとう', meaning: 'Lampu warning' },
  { id: 658, kanji: 'アラーム', reading: 'アラーム', meaning: 'Alarm' },
  { id: 659, kanji: '点灯', reading: 'てんとう', meaning: 'Menyala' },
  { id: 660, kanji: '点滅', reading: 'てんめつ', meaning: 'Berkedip' },
  // Additive & Pengawet
  { id: 661, kanji: '保存料', reading: 'ほぞんりょう', meaning: 'Bahan pengawet' },
  { id: 662, kanji: '着色料', reading: 'ちゃくしょくりょう', meaning: 'Pewarna' },
  { id: 663, kanji: '香料', reading: 'こうりょう', meaning: 'Perasa' },
  { id: 664, kanji: '甘味料', reading: 'かんみりょう', meaning: 'Pemanis' },
  { id: 665, kanji: '酸化防止剤', reading: 'さんかぼうしざい', meaning: 'Antioksidan' },
  { id: 666, kanji: '防カビ剤', reading: 'ぼうカビざい', meaning: 'Anti jamur' },
  { id: 667, kanji: '乳化剤', reading: 'にゅうかざい', meaning: 'Emulsifier' },
  { id: 668, kanji: '安定剤', reading: 'あんていざい', meaning: 'Stabilizer' },
  { id: 669, kanji: '膨張剤', reading: 'ぼうちょうざい', meaning: 'Bahan pengembang' },
  // Organisasi & SDM
  { id: 670, kanji: '交代', reading: 'こうたい', meaning: 'Ganti shift' },
  { id: 671, kanji: '昼休み', reading: 'ひるやすみ', meaning: 'Istirahat siang' },
  { id: 672, kanji: '残業', reading: 'ざんぎょう', meaning: 'Lembur' },
  { id: 673, kanji: 'シフト', reading: 'シフト', meaning: 'Shift' },
  { id: 674, kanji: '上司', reading: 'じょうし', meaning: 'Atasan' },
  { id: 675, kanji: '部下', reading: 'ぶか', meaning: 'Bawahan' },
  { id: 676, kanji: '先輩', reading: 'せんぱい', meaning: 'Senior' },
  { id: 677, kanji: '後輩', reading: 'こうはい', meaning: 'Junior' },
  { id: 678, kanji: '新人', reading: 'しんじん', meaning: 'Karyawan baru' },
  { id: 679, kanji: '作業日報', reading: 'さぎょうにっぽう', meaning: 'Laporan harian' },
  { id: 680, kanji: '目標', reading: 'もくひょう', meaning: 'Target' },
  { id: 681, kanji: '規則', reading: 'きそく', meaning: 'Peraturan' },
  { id: 682, kanji: '遵守', reading: 'じゅんしゅ', meaning: 'Kepatuhan' },
  { id: 683, kanji: '改善提案', reading: 'かいぜんていあん', meaning: 'Kaizen proposal' },
  { id: 684, kanji: '効率', reading: 'こうりつ', meaning: 'Efisiensi' },
  { id: 685, kanji: '無駄', reading: 'むだ', meaning: 'Pemborosan' },
  { id: 686, kanji: '生産性', reading: 'せいさんせい', meaning: 'Produktivitas' },
  { id: 687, kanji: '緊急', reading: 'きんきゅう', meaning: 'Darurat' },
  { id: 688, kanji: '対応', reading: 'たいおう', meaning: 'Penanganan' },
  { id: 689, kanji: '役割', reading: 'やくわり', meaning: 'Peran' },
  { id: 690, kanji: '工場長', reading: 'こうじょうちょう', meaning: 'Kepala pabrik' },
  { id: 691, kanji: '班長', reading: 'はんちょう', meaning: 'Hancho' },
  { id: 692, kanji: '作業員', reading: 'さぎょういん', meaning: 'Operator' },
  { id: 693, kanji: '実習生', reading: 'じっしゅうせい', meaning: 'Pemagang' },
  { id: 694, kanji: '従業員', reading: 'じゅうぎょういん', meaning: 'Karyawan' },
  // Keselamatan Kebakaran & Darurat
  { id: 695, kanji: '消火栓', reading: 'しょうかせん', meaning: 'Hidran' },
  { id: 696, kanji: '火災報知器', reading: 'かさいほうちき', meaning: 'Alarm kebakaran' },
  { id: 697, kanji: '非常口', reading: 'ひじょうぐち', meaning: 'Pintu darurat' },
  { id: 698, kanji: '是正処置', reading: 'ぜせいしょち', meaning: 'Tindakan korektif' },
  { id: 699, kanji: '予防処置', reading: 'よぼうしょち', meaning: 'Tindakan preventif' },
  { id: 700, kanji: '内部監査', reading: 'ないぶかんさ', meaning: 'Audit internal' },
  { id: 701, kanji: '外部監査', reading: 'がいぶかんさ', meaning: 'Audit eksternal' },
  { id: 702, kanji: 'ISO', reading: 'ISO', meaning: 'ISO' },
  { id: 703, kanji: '有機', reading: 'ゆうき', meaning: 'Organik' },
  { id: 704, kanji: '無農薬', reading: 'むのうやく', meaning: 'Tanpa pestisida' },
  { id: 705, kanji: '残留農薬', reading: 'ざんりゅうのうやく', meaning: 'Residu pestisida' },
  { id: 706, kanji: '可燃物', reading: 'かねんぶつ', meaning: 'Mudah terbakar' },
  { id: 707, kanji: '頭上注意', reading: 'ずじょうちゅうい', meaning: 'Awas atas' },
  { id: 708, kanji: '静電気', reading: 'せいでんき', meaning: 'Listrik statis' },
  // Limbah & Lingkungan
  { id: 709, kanji: '産業廃棄物', reading: 'さんぎょうはいきぶつ', meaning: 'Limbah industri' },
  { id: 710, kanji: '生ゴミ', reading: 'なまゴミ', meaning: 'Sampah organik' },
  { id: 711, kanji: '分別', reading: 'ぶんべつ', meaning: 'Pemilahan sampah' },
  { id: 712, kanji: 'リサイクル', reading: 'リサイクル', meaning: 'Daur ulang' },
  { id: 713, kanji: '廃水', reading: 'はいすい', meaning: 'Air limbah' },
  { id: 714, kanji: '排水処理', reading: 'はいすいしょり', meaning: 'Pengolahan air limbah' },
  // Sifat Ukuran & Jumlah
  { id: 715, kanji: '古い', reading: 'ふるい', meaning: 'Basi/Lama' },
  { id: 716, kanji: '湿っている', reading: 'しめっている', meaning: 'Lembab' },
  { id: 717, kanji: '乾いている', reading: 'かわいている', meaning: 'Kering' },
  { id: 718, kanji: '太い', reading: 'ふとい', meaning: 'Tebal/Gemuk' },
  { id: 719, kanji: '細い', reading: 'ほそい', meaning: 'Tipis/Kurus' },
  { id: 720, kanji: '厚い', reading: 'あつい', meaning: 'Tebal' },
  { id: 721, kanji: '長い', reading: 'ながい', meaning: 'Panjang' },
  { id: 722, kanji: '短い', reading: 'みじかい', meaning: 'Pendek' },
  { id: 723, kanji: '大きい', reading: 'おおきい', meaning: 'Besar' },
  { id: 724, kanji: '小さい', reading: 'ちいさい', meaning: 'Kecil' },
  { id: 725, kanji: '多い', reading: 'おおい', meaning: 'Banyak' },
  { id: 726, kanji: '少ない', reading: 'すくない', meaning: 'Sedikit' },
  { id: 727, kanji: '足りない', reading: 'たりない', meaning: 'Kurang' },
  { id: 728, kanji: '余る', reading: 'あまる', meaning: 'Sisa' },
  { id: 729, kanji: '違う', reading: 'ちがう', meaning: 'Berbeda' },
  { id: 730, kanji: '良い匂い', reading: 'いいにおい', meaning: 'Wangi' },
  // Tekstur Lanjutan
  { id: 731, kanji: 'トロトロ', reading: 'トロトロ', meaning: 'Kental lembut' },
  { id: 732, kanji: 'パサパサ', reading: 'パサパサ', meaning: 'Kering rapuh' },
  { id: 733, kanji: 'しっとり', reading: 'しっとり', meaning: 'Lembab halus' },
  { id: 734, kanji: 'ぐちゃぐちゃ', reading: 'ぐちゃぐちゃ', meaning: 'Benyek' },
  { id: 735, kanji: 'ボロボロ', reading: 'ボロボロ', meaning: 'Remuk' },
  { id: 736, kanji: 'ザラザラ', reading: 'ザラザラ', meaning: 'Kasar' },
  { id: 737, kanji: 'ツルツル', reading: 'ツルツル', meaning: 'Licin' },
  { id: 738, kanji: '透明', reading: 'とうめい', meaning: 'Bening' },
  { id: 739, kanji: '不透明', reading: 'ふとうめい', meaning: 'Buram' },
  { id: 740, kanji: '濁る', reading: 'にごる', meaning: 'Keruh' },
  { id: 741, kanji: '澄む', reading: 'すむ', meaning: 'Jernih' },
  // Proses Memasak & Kondisi
  { id: 742, kanji: '解体', reading: 'かいたい', meaning: 'Pembongkaran/Pemotongan' },
  { id: 743, kanji: '練り込む', reading: 'ねりこむ', meaning: 'Menguleni' },
  { id: 744, kanji: '打ち粉', reading: 'うちこ', meaning: 'Tepung tabur' },
  { id: 745, kanji: '粗熱を取る', reading: 'あらねつをとる', meaning: 'Mendinginkan sebentar' },
  { id: 746, kanji: '湯煎', reading: 'ゆせん', meaning: 'Mengetim (bain-marie)' },
  { id: 747, kanji: '煮詰める', reading: 'につめる', meaning: 'Merebus hingga kental' },
  { id: 748, kanji: '焦げ付く', reading: 'こげつく', meaning: 'Gosong menempel' },
  { id: 749, kanji: '蒸発', reading: 'じょうはつ', meaning: 'Penguapan' },
  { id: 750, kanji: '圧搾', reading: 'あっさく', meaning: 'Mengepres' },
  { id: 751, kanji: '生', reading: 'なま', meaning: 'Mentah' },
  { id: 752, kanji: '半生', reading: 'はんなま', meaning: 'Setengah matang' },
  { id: 753, kanji: '煮える', reading: 'にえる', meaning: 'Matang rebus' },
  { id: 754, kanji: '焼ける', reading: 'やける', meaning: 'Matang panggang' },
  { id: 755, kanji: '揚がる', reading: 'あがる', meaning: 'Matang goreng' },
  { id: 756, kanji: '浸す', reading: 'ひたす', meaning: 'Merendam' },
  { id: 757, kanji: '漬ける', reading: 'つける', meaning: 'Merendam bumbu' },
  { id: 758, kanji: '塗る', reading: 'ぬる', meaning: 'Mengoles' },
  { id: 759, kanji: '振りかける', reading: 'ふりかける', meaning: 'Menabur' },
  { id: 760, kanji: '濾す', reading: 'こす', meaning: 'Menyaring' },
  { id: 761, kanji: '水気を切る', reading: 'みずけをきる', meaning: 'Meniriskan' },
  { id: 762, kanji: '泡', reading: 'あわ', meaning: 'Busa' },
  { id: 763, kanji: '泡立つ', reading: 'あわだつ', meaning: 'Berbusa' },
  { id: 764, kanji: '研ぐ', reading: 'とぐ', meaning: 'Mengasah' },
  { id: 765, kanji: '叩く', reading: 'たたく', meaning: 'Memukul/Menepuk' },
  { id: 766, kanji: '潰す', reading: 'つぶす', meaning: 'Menghancurkan' },
  { id: 767, kanji: '燃える', reading: 'もえる', meaning: 'Terbakar' },
  { id: 768, kanji: '焦げる', reading: 'こげる', meaning: 'Gosong' },
  // Kondisi Fisik Produk & Kemasan
  { id: 769, kanji: '空', reading: 'から', meaning: 'Kosong' },
  { id: 770, kanji: '満タン', reading: 'まんタン', meaning: 'Penuh' },
  { id: 771, kanji: '詰まる', reading: 'つまる', meaning: 'Tersumbat' },
  { id: 772, kanji: '溢れる', reading: 'こぼれる', meaning: 'Tumpah' },
  { id: 773, kanji: '滴る', reading: 'したたる', meaning: 'Menetes' },
  { id: 774, kanji: '破れる', reading: 'やぶれる', meaning: 'Robek' },
  { id: 775, kanji: '割れる', reading: 'われる', meaning: 'Pecah' },
  { id: 776, kanji: '折れる', reading: 'おれる', meaning: 'Patah' },
  { id: 777, kanji: '曲がる', reading: 'まがる', meaning: 'Bengkok' },
  { id: 778, kanji: '凹む', reading: 'へこむ', meaning: 'Penyok' },
  { id: 779, kanji: 'ズレる', reading: 'ズレる', meaning: 'Bergeser' },
  { id: 780, kanji: '剥がれる', reading: 'はがれる', meaning: 'Terkelupas' },
  { id: 781, kanji: '溶ける', reading: 'とける', meaning: 'Meleleh' },
  { id: 782, kanji: '固まる', reading: 'かたまる', meaning: 'Mengeras' },
  { id: 783, kanji: '蒸発する', reading: 'じょうはつする', meaning: 'Menguap' },
  // Logistik & Kemasan Tambahan
  { id: 784, kanji: '結束する', reading: 'けっそくする', meaning: 'Mengikat' },
  { id: 785, kanji: 'テープ', reading: 'テープ', meaning: 'Lakban' },
  { id: 786, kanji: '紐', reading: 'ひも', meaning: 'Tali' },
  { id: 787, kanji: 'バンド', reading: 'バンド', meaning: 'Strapping band' },
  { id: 788, kanji: '箱詰め', reading: 'はこづめ', meaning: 'Masuk kardus' },
  { id: 789, kanji: 'QRコード', reading: 'QRコード', meaning: 'QR code' },
  { id: 790, kanji: '宛先', reading: 'あてさき', meaning: 'Alamat tujuan' },
  { id: 791, kanji: '出庫', reading: 'しゅっこ', meaning: 'Barang keluar' },
  { id: 792, kanji: '入庫', reading: 'にゅうこ', meaning: 'Barang masuk' },
  { id: 793, kanji: '荷姿', reading: 'にすがた', meaning: 'Bentuk kemasan' },
  { id: 794, kanji: '荷崩れ', reading: 'にくずれ', meaning: 'Runtuh/berantakan' },
  { id: 795, kanji: '積み重ね', reading: 'つみかさね', meaning: 'Menumpuk' },
  { id: 796, kanji: '荷受人', reading: 'にうけにん', meaning: 'Penerima' },
  { id: 797, kanji: '差出人', reading: 'さしだしにん', meaning: 'Pengirim' },
  { id: 798, kanji: '伝票番号', reading: 'でんぴょうばんごう', meaning: 'No. Resi' },
  { id: 799, kanji: '納期', reading: 'のうき', meaning: 'Deadline pengiriman' },
  // Satuan & Pengukuran
  { id: 800, kanji: 'グラム', reading: 'グラム', meaning: 'Gram' },
  { id: 801, kanji: 'キログラム', reading: 'キログラム', meaning: 'Kilogram' },
  { id: 802, kanji: 'リットル', reading: 'リットル', meaning: 'Liter' },
  { id: 803, kanji: 'ミリリットル', reading: 'ミリリットル', meaning: 'Mililiter' },
  { id: 804, kanji: 'パーセント', reading: 'パーセント', meaning: 'Persen' },
  { id: 805, kanji: '平均', reading: 'へいきん', meaning: 'Rata-rata' },
  { id: 806, kanji: '合計', reading: 'ごうけい', meaning: 'Jumlah total' },
  { id: 807, kanji: '残り', reading: 'のこり', meaning: 'Sisa' },
  { id: 808, kanji: '過剰', reading: 'かじょう', meaning: 'Berlebih' },
  { id: 809, kanji: '不足', reading: 'ふそく', meaning: 'Kurang' },
  { id: 810, kanji: '数量', reading: 'すうりょう', meaning: 'Kuantitas' },
  { id: 811, kanji: '濁度', reading: 'だくど', meaning: 'Kekeruhan' },
  { id: 812, kanji: '気体', reading: 'きたい', meaning: 'Gas' },
  { id: 813, kanji: '酸味料', reading: 'さんみりょう', meaning: 'Pengatur keasaman' },
  { id: 814, kanji: '凝固剤', reading: 'ぎょうこざい', meaning: 'Penggumpal' },
  { id: 815, kanji: '電流', reading: 'でんりゅう', meaning: 'Arus listrik' },
  { id: 816, kanji: '流量', reading: 'りゅうりょう', meaning: 'Debit' },
  { id: 817, kanji: '回転数', reading: 'かいてんすう', meaning: 'RPM' },
  { id: 818, kanji: '設定値', reading: 'せっていち', meaning: 'Setting value' },
  { id: 819, kanji: '測定値', reading: 'そくていち', meaning: 'Measured value' },
  { id: 820, kanji: '範囲', reading: 'はんい', meaning: 'Range/Rentang' },
  // Maintenance & Operasi Mesin Lanjutan
  { id: 821, kanji: '保守', reading: 'ほしゅ', meaning: 'Pemeliharaan' },
  { id: 822, kanji: '清掃道具', reading: 'せいそうどうぐ', meaning: 'Alat kebersihan' },
  { id: 823, kanji: '停止中', reading: 'ていしちゅう', meaning: 'Sedang berhenti' },
  { id: 824, kanji: '準備中', reading: 'じゅんびちゅう', meaning: 'Sedang persiapan' },
  { id: 825, kanji: '運転', reading: 'うんてん', meaning: 'Operasi mesin' },
  { id: 826, kanji: '作動', reading: 'さどう', meaning: 'Berfungsi' },
  { id: 827, kanji: '試運転', reading: 'しうんてん', meaning: 'Tes run' },
  { id: 828, kanji: '異音', reading: 'いおん', meaning: 'Suara aneh' },
  { id: 829, kanji: '締め付け', reading: 'しめつけ', meaning: 'Pengencangan' },
  { id: 830, kanji: 'スパナ', reading: 'スパナ', meaning: 'Kunci pas' },
  { id: 831, kanji: 'ペンチ', reading: 'ペンチ', meaning: 'Tang' },
  { id: 832, kanji: '給油', reading: 'きゅうゆ', meaning: 'Pengisian oli' },
  { id: 833, kanji: '注油', reading: 'ちゅうゆ', meaning: 'Memberi minyak' },
  { id: 834, kanji: 'グリース', reading: 'グリース', meaning: 'Gemuk/Grease' },
  { id: 835, kanji: 'エラー', reading: 'エラー', meaning: 'Error' },
  { id: 836, kanji: '消灯', reading: 'しょうとう', meaning: 'Lampu mati' },
  { id: 837, kanji: '故障中', reading: 'こしょうちゅう', meaning: 'Sedang rusak' },
  { id: 838, kanji: '使用禁止', reading: 'しようきんし', meaning: 'Dilarang pakai' },
  { id: 839, kanji: '水漏れ', reading: 'みずもれ', meaning: 'Bocor air' },
  { id: 840, kanji: '油漏れ', reading: 'あぶらもれ', meaning: 'Bocor minyak' },
  { id: 841, kanji: '空気漏れ', reading: 'くうきもれ', meaning: 'Bocor udara' },
  { id: 842, kanji: '蒸気漏れ', reading: 'じょうきもれ', meaning: 'Bocor uap' },
  { id: 843, kanji: 'ヒューズ', reading: 'ヒューズ', meaning: 'Sekring' },
  { id: 844, kanji: '鳴る', reading: 'なる', meaning: 'Berbunyi' },
  // Verbs Tambahan
  { id: 845, kanji: '揃える', reading: 'そろえる', meaning: 'Meratakan/Menyamakan' },
  { id: 846, kanji: '結ぶ', reading: 'むすぶ', meaning: 'Mengikat' },
  { id: 847, kanji: '施錠する', reading: 'せじょうする', meaning: 'Mengunci' },
  { id: 848, kanji: '直す', reading: 'なおす', meaning: 'Membetulkan' },
  { id: 849, kanji: '組み立てる', reading: 'くみたてる', meaning: 'Merakit' },
  { id: 850, kanji: '分解する', reading: 'ぶんかいする', meaning: 'Membongkar' },
  { id: 851, kanji: '用意する', reading: 'よういする', meaning: 'Menyediakan' },
  { id: 852, kanji: '続く', reading: 'つづく', meaning: 'Berlanjut' },
  { id: 853, kanji: '続ける', reading: 'つづける', meaning: 'Melanjutkan' },
  { id: 854, kanji: '生産する', reading: 'せいさんする', meaning: 'Memproduksi' },
  { id: 855, kanji: '遠心分離', reading: 'えんしんぶんり', meaning: 'Sentrifugal' },
  { id: 856, kanji: '調合', reading: 'ちょうごう', meaning: 'Pencampuran bahan' },
  { id: 857, kanji: '目視する', reading: 'もくしする', meaning: 'Memeriksa secara visual' },
  { id: 858, kanji: '触診', reading: 'しょくしん', meaning: 'Pemeriksaan sentuh' },
  { id: 859, kanji: '抜き打ち', reading: 'ぬきうち', meaning: 'Inspeksi dadakan' },
  // Organisasi & SDM Lanjutan
  { id: 860, kanji: '早退', reading: 'そうたい', meaning: 'Pulang cepat' },
  { id: 861, kanji: '遅刻', reading: 'ちこく', meaning: 'Terlambat' },
  { id: 862, kanji: '欠勤', reading: 'けっきん', meaning: 'Absen' },
  { id: 863, kanji: '有給休暇', reading: 'ゆうきゅうきゅうか', meaning: 'Cuti berbayar' },
  { id: 864, kanji: '日勤', reading: 'にっきん', meaning: 'Shift siang' },
  { id: 865, kanji: '夜勤', reading: 'やきん', meaning: 'Shift malam' },
  { id: 866, kanji: '当番', reading: 'とうばん', meaning: 'Piket' },
  { id: 867, kanji: '指示書', reading: 'しじしょ', meaning: 'Instruksi tertulis' },
  { id: 868, kanji: '研修生', reading: 'けんしゅうせい', meaning: 'Trainee' },
  { id: 869, kanji: '会社', reading: 'かいしゃ', meaning: 'Perusahaan' },
  { id: 870, kanji: '権利', reading: 'けんり', meaning: 'Hak' },
  { id: 871, kanji: '許可', reading: 'きょか', meaning: 'Izin' },
  { id: 872, kanji: '承認', reading: 'しょうにん', meaning: 'Persetujuan' },
  { id: 873, kanji: '却下', reading: 'きゃっか', meaning: 'Penolakan' },
  { id: 874, kanji: '提案', reading: 'ていあん', meaning: 'Proposal' },
  { id: 875, kanji: 'コスト', reading: 'コスト', meaning: 'Biaya' },
  { id: 876, kanji: '削減', reading: 'さくげん', meaning: 'Pengurangan biaya' },
  { id: 877, kanji: '向上', reading: 'こうじょう', meaning: 'Peningkatan' },
  { id: 878, kanji: '低下', reading: 'ていか', meaning: 'Penurunan' },
  { id: 879, kanji: '変更', reading: 'へんこう', meaning: 'Perubahan' },
  { id: 880, kanji: 'キャンセル', reading: 'キャンセル', meaning: 'Batal' },
  { id: 881, kanji: '延期', reading: 'えんき', meaning: 'Tunda' },
  { id: 882, kanji: '調整', reading: 'ちょうせい', meaning: 'Koordinasi' },
  { id: 883, kanji: '打ち合わせ', reading: 'うちあわせ', meaning: 'Meeting singkat' },
  { id: 884, kanji: '引継ぎ', reading: 'ひきつぎ', meaning: 'Serah terima' },
  { id: 885, kanji: '共有', reading: 'きょうゆう', meaning: 'Berbagi informasi' },
  { id: 886, kanji: '優先順位', reading: 'ゆうせんじゅんい', meaning: 'Prioritas' },
  { id: 887, kanji: '至急', reading: 'しきゅう', meaning: 'Segera' },
  { id: 888, kanji: '処理', reading: 'しょり', meaning: 'Proses' },
  { id: 889, kanji: '実行', reading: 'じっこう', meaning: 'Eksekusi' },
  { id: 890, kanji: '達成', reading: 'たっせい', meaning: 'Tercapai' },
  { id: 891, kanji: 'タイムカード', reading: 'タイムカード', meaning: 'Kartu absen' },
  { id: 892, kanji: '打刻', reading: 'だこく', meaning: 'Tap kartu' },
  { id: 893, kanji: '給料', reading: 'きゅうりょう', meaning: 'Gaji' },
  { id: 894, kanji: '給与明細', reading: 'きゅうよめいさい', meaning: 'Slip gaji' },
  { id: 895, kanji: '休憩室', reading: 'きゅうけいしつ', meaning: 'Ruang istirahat' },
  { id: 896, kanji: '更衣室', reading: 'こういしつ', meaning: 'Ruang ganti' },
  { id: 897, kanji: 'ロッカー', reading: 'ロッカー', meaning: 'Loker' },
  { id: 898, kanji: '食堂', reading: 'しょくどう', meaning: 'Kantin' },
  { id: 899, kanji: '事務所', reading: 'じむしょ', meaning: 'Kantor' },
  { id: 900, kanji: '現場', reading: 'げんば', meaning: 'Lokasi kerja' },
  // HR & Regulasi
  { id: 901, kanji: '就業規則', reading: 'しゅうぎょうきそく', meaning: 'Peraturan perusahaan' },
  { id: 902, kanji: '雇用契約書', reading: 'こようけいやくしょ', meaning: 'Kontrak kerja' },
  { id: 903, kanji: '健康保険', reading: 'けんこうほけん', meaning: 'Asuransi kesehatan' },
  { id: 904, kanji: '厚生年金', reading: 'こうせいねんきん', meaning: 'Pensiun' },
  { id: 905, kanji: '税金', reading: 'ぜいきん', meaning: 'Pajak' },
  { id: 906, kanji: '査定', reading: 'さてい', meaning: 'Penilaian kinerja' },
  { id: 907, kanji: '昇給', reading: 'しょうきゅう', meaning: 'Kenaikan gaji' },
  { id: 908, kanji: '賞与', reading: 'しょうよ', meaning: 'Bonus' },
  { id: 909, kanji: '手当', reading: 'てあて', meaning: 'Tunjangan' },
  { id: 910, kanji: '残業代', reading: 'ざんぎょうだい', meaning: 'Upah lembur' },
  { id: 911, kanji: '解雇', reading: 'かいこ', meaning: 'PHK' },
  { id: 912, kanji: '退職', reading: 'たいしょく', meaning: 'Resign' },
  { id: 913, kanji: '退職届', reading: 'たいしょくとどけ', meaning: 'Surat resign' },
  { id: 914, kanji: '試用期間', reading: 'しようきかん', meaning: 'Masa probation' },
  { id: 915, kanji: '本採用', reading: 'ほんさいよう', meaning: 'Karyawan tetap' },
  // Keamanan & Rambu Tambahan
  { id: 916, kanji: '防犯カメラ', reading: 'ぼうはんカメラ', meaning: 'CCTV' },
  { id: 917, kanji: '入室', reading: 'にゅうしつ', meaning: 'Masuk ruangan' },
  { id: 918, kanji: '退室', reading: 'たいしつ', meaning: 'Keluar ruangan' },
  { id: 919, kanji: '認証', reading: 'にんしょう', meaning: 'Verifikasi' },
  { id: 920, kanji: 'IDカード', reading: 'IDカード', meaning: 'Kartu ID' },
  { id: 921, kanji: '防爆', reading: 'ぼうばく', meaning: 'Anti ledak' },
  { id: 922, kanji: '不燃物', reading: 'ふねんぶつ', meaning: 'Tidak mudah terbakar' },
  { id: 923, kanji: '喫煙所', reading: 'きつえんじょ', meaning: 'Area merokok' },
  { id: 924, kanji: '開口部', reading: 'かいこうぶ', meaning: 'Celah/Bukaan' },
  { id: 925, kanji: '隙間', reading: 'すきま', meaning: 'Sela' },
  { id: 926, kanji: '水平', reading: 'すいへい', meaning: 'Horizontal' },
  { id: 927, kanji: '垂直', reading: 'すいちょく', meaning: 'Vertikal' },
  { id: 928, kanji: '傾斜', reading: 'けいしゃ', meaning: 'Kemiringan' },
  { id: 929, kanji: '照度', reading: 'しょうど', meaning: 'Iluminasi' },
  { id: 930, kanji: '逸脱', reading: 'いつだつ', meaning: 'Penyimpangan' },
  { id: 931, kanji: '是正', reading: 'ぜせい', meaning: 'Perbaikan/Koreksi' },
  { id: 932, kanji: '審査', reading: 'しんさ', meaning: 'Pemeriksaan' },
  { id: 933, kanji: '認証機関', reading: 'にんしょうきかん', meaning: 'Badan sertifikasi' },
  { id: 934, kanji: '遺伝子組み換え', reading: 'いでんしくみかえ', meaning: 'GMO' },
  { id: 935, kanji: '検疫', reading: 'けんえき', meaning: 'Karantina' },
  { id: 936, kanji: '通関', reading: 'つうかん', meaning: 'Bea cukai' },
  // Transportasi & Dokumen
  { id: 937, kanji: '冷凍コンテナ', reading: 'れいとうコンテナ', meaning: 'Reefer container' },
  { id: 938, kanji: '船便', reading: 'ふなびん', meaning: 'Pengiriman laut' },
  { id: 939, kanji: '航空便', reading: 'こうくうびん', meaning: 'Pengiriman udara' },
  { id: 940, kanji: 'トラック', reading: 'トラック', meaning: 'Truk' },
  { id: 941, kanji: '運転手', reading: 'うんてんしゅ', meaning: 'Sopir' },
  { id: 942, kanji: '荷台', reading: 'にだい', meaning: 'Bak truk' },
  { id: 943, kanji: '積み込む', reading: 'つみこむ', meaning: 'Memuat barang' },
  { id: 944, kanji: '降ろす', reading: 'おろす', meaning: 'Menurunkan barang' },
  { id: 945, kanji: '荷主', reading: 'にぬし', meaning: 'Pemilik barang' },
  { id: 946, kanji: '受領書', reading: 'じゅりょうしょ', meaning: 'Tanda terima' },
  { id: 947, kanji: '請求書', reading: 'せいきゅうしょ', meaning: 'Invoice/Tagihan' },
  { id: 948, kanji: '納品書', reading: 'のうひんしょ', meaning: 'Surat jalan' },
  { id: 949, kanji: '見積書', reading: 'みつもりしょ', meaning: 'Penawaran harga' },
  { id: 950, kanji: '発注書', reading: 'はっちゅうしょ', meaning: 'Purchase order' },
  { id: 951, kanji: 'クライアント', reading: 'クライアント', meaning: 'Klien' },
  // Dokumen Internal & Komunikasi
  { id: 952, kanji: '申し送り', reading: 'もうしおくり', meaning: 'Serah terima shift' },
  { id: 953, kanji: '議事録', reading: 'ぎじろく', meaning: 'Notulen rapat' },
  { id: 954, kanji: '掲示板', reading: 'けいじばん', meaning: 'Papan pengumuman' },
  { id: 955, kanji: '回覧', reading: 'かいらん', meaning: 'Edaran' },
  { id: 956, kanji: '周知徹底', reading: 'しゅうちてってい', meaning: 'Sosialisasi menyeluruh' },
  { id: 957, kanji: '見直す', reading: 'みなおす', meaning: 'Meninjau ulang' },
  { id: 958, kanji: '修正', reading: 'しゅうせい', meaning: 'Revisi' },
  { id: 959, kanji: '更新', reading: 'こうしん', meaning: 'Update' },
  { id: 960, kanji: '理解', reading: 'りかい', meaning: 'Pemahaman' },
  { id: 961, kanji: '命令', reading: 'めいれい', meaning: 'Perintah' },
  { id: 962, kanji: '高圧', reading: 'こうあつ', meaning: 'Tekanan tinggi' },
  // Lingkungan & Sampah Tambahan
  { id: 963, kanji: '一般廃棄物', reading: 'いっぱんはいきぶつ', meaning: 'Limbah umum' },
  { id: 964, kanji: '汚水', reading: 'おすい', meaning: 'Air kotor' },
  { id: 965, kanji: '悪臭', reading: 'あくしゅう', meaning: 'Bau busuk' },
  { id: 966, kanji: '脱臭', reading: 'だっしゅう', meaning: 'Penghilangan bau' },
]
