// Auto-generated by gen_enc_token.py — do not edit manually.
// XOR-obfuscated credentials for Vercel deployment (no env-var setup needed).
// Rotate by editing .env then re-running: python3 gen_enc_token.py
const _k = 'jft-rananwari-studyverse-leaderboard-2026'
const _t = 'DQ4Ecgg4HjlYOCtCBkgFIxwTICASJBQHfw5ULlJUSiguL0Ivd2ZyAg=='
const _r = 'AhIAXQFbQU4JHhUaHE9dFxoJVgcGChoLWUEGEx0VBg1AFhcGAHh2Zg=='
const _b = 'BwcdQw=='

function _d(enc: string): string {
  if (!enc) return ''
  try {
    const bytes = Buffer.from(enc, 'base64')
    return Buffer.from(bytes.map((b, i) => b ^ _k.charCodeAt(i % _k.length))).toString('utf8')
  } catch {
    return ''
  }
}

export const bundledToken   = _d(_t)
export const bundledRepoUrl = _d(_r)
export const bundledBranch  = _d(_b)
