export const allKanjiN3 = [
    { id: 1, kanji: '企画', reading: 'きかく', meaning: 'Perencanaan/Proyek' },
    { id: 2, kanji: '勤務', reading: 'きんむ', meaning: 'Dinas/Kerja' },
    { id: 3, kanji: '効率', reading: 'こうりつ', meaning: 'Efisiensi' },
    { id: 4, kanji: '在庫', reading: 'ざいこ', meaning: 'Stok persediaan' },
    { id: 5, kanji: '信頼', reading: 'しんらい', meaning: 'Kepercayaan' },
    { id: 6, kanji: '設備', reading: 'せつび', meaning: 'Fasilitas/Peralatan' },
    { id: 7, kanji: '存在', reading: 'そんざい', meaning: 'Keberadaan' },
    { id: 8, kanji: '対応', reading: 'たいおう', meaning: 'Penanganan/Respons' },
    { id: 9, kanji: '知識', reading: 'ちしき', meaning: 'Pengetahuan' },
    { id: 10, kanji: '通知', reading: 'つうち', meaning: 'Pemberitahuan' },
    { id: 11, kanji: '手順', reading: 'てじゅん', meaning: 'Prosedur/Langkah' },
    { id: 12, kanji: '点検', reading: 'てんけん', meaning: 'Pemeriksaan' },
    { id: 13, kanji: '内容', reading: 'ないよう', meaning: 'Isi/Konten' },
    { id: 14, kanji: '分野', reading: 'ぶんや', meaning: 'Bidang' },
    { id: 15, kanji: '変更', reading: 'へんこう', meaning: 'Perubahan' },
    { id: 16, kanji: '満足', reading: 'まんぞく', meaning: 'Kepuasan' },
    { id: 17, kanji: '魅力', reading: 'みりょく', meaning: 'Daya tarik' },
    { id: 18, kanji: '迷惑', reading: 'めいわく', meaning: 'Gangguan/Kerugian' },
    { id: 19, kanji: '予定', reading: 'よてい', meaning: 'Rencana/Jadwal' },
    { id: 20, kanji: '連想', reading: 'れんそう', meaning: 'Asosiasi/Imajinasi' },
    { id: 21, kanji: '労働', reading: 'ろうどう', meaning: 'Tenaga kerja' },
    { id: 22, kanji: '安定', reading: 'あんてい', meaning: 'Stabilitas' },
    { id: 23, kanji: '一般', reading: 'いっぱん', meaning: 'Umum' },
    { id: 24, kanji: '受付', reading: 'うけつけ', meaning: 'Resepsionis/Penerimaan' },
    { id: 25, kanji: '応援', reading: 'おうえん', meaning: 'Dukungan' },
    { id: 26, kanji: '解決', reading: 'かいけつ', meaning: 'Penyelesaian' },
    { id: 27, kanji: '確認', reading: 'かくにん', meaning: 'Konfirmasi' },
    { id: 28, kanji: '関係', reading: 'かんけい', meaning: 'Hubungan' },
    { id: 29, kanji: '希望', reading: 'きぼう', meaning: 'Harapan' },
    { id: 30, kanji: '疑問', reading: 'ぎもん', meaning: 'Keraguan/Pertanyaan' },
    { id: 31, kanji: '経験', reading: 'けいけん', meaning: 'Pengalaman' },
    { id: 32, kanji: '結果', reading: 'けっか', meaning: 'Hasil' },
    { id: 33, kanji: '行動', reading: 'こうどう', meaning: 'Tindakan' },
    { id: 34, kanji: '作業', reading: 'さぎょう', meaning: 'Pekerjaan/Proses kerja' },
    { id: 35, kanji: '資源', reading: 'しげん', meaning: 'Sumber daya' },
    { id: 36, kanji: '生産', reading: 'せいさん', meaning: 'Produksi' },
    { id: 37, kanji: '整理', reading: 'せいり', meaning: 'Pengaturan/Merapikan' },
    { id: 38, kanji: '節約', reading: 'せつやく', meaning: 'Penghematan' },
    { id: 39, kanji: '選択', reading: 'せんたく', meaning: 'Pilihan' },
    { id: 40, kanji: '速度', reading: 'そくど', meaning: 'Kecepatan' },
    { id: 41, kanji: '体験', reading: 'たいけん', meaning: 'Pengalaman' },
    { id: 42, kanji: '担当', reading: 'たんとう', meaning: 'Tanggung jawab/Bagian' },
    { id: 43, kanji: '提案', reading: 'ていあん', meaning: 'Usulan' },
    { id: 44, kanji: '展望', reading: 'てんぼう', meaning: 'Pandangan/Prospek' },
    { id: 45, kanji: '努力', reading: 'どりょく', meaning: 'Usaha keras' },
    { id: 46, kanji: '人気', reading: 'にんき', meaning: 'Populer' },
    { id: 47, kanji: '熱心', reading: 'ねっしん', meaning: 'Antusias' },
    { id: 48, kanji: '発見', reading: 'はっけん', meaning: 'Penemuan' },
    { id: 49, kanji: '判断', reading: 'はんだん', meaning: 'Keputusan/Penilaian' },
    { id: 50, kanji: '批判', reading: 'ひはん', meaning: 'Kritik' },
    { id: 51, kanji: '不安', reading: 'ふあん', meaning: 'Kecemasan' },
    { id: 52, kanji: '不足', reading: 'ふそく', meaning: 'Kekurangan' },
    { id: 53, kanji: '平均', reading: 'へいきん', meaning: 'Rata-rata' },
    { id: 54, kanji: '募集', reading: 'ぼしゅう', meaning: 'Perekrutan' },
    { id: 55, kanji: '翻訳', reading: 'ほんやく', meaning: 'Terjemahan' },
    { id: 56, kanji: '間違い', reading: 'まちがい', meaning: 'Kesalahan' },
    { id: 57, kanji: '無料', reading: 'むりょう', meaning: 'Gratis' },
    { id: 58, kanji: '免許', reading: 'めんきょ', meaning: 'Lisensi/SIM' },
    { id: 59, kanji: '役割', reading: 'やくわり', meaning: 'Peran' },
    { id: 60, kanji: '理解', reading: 'りかい', meaning: 'Pemahaman' },
    { id: 61, kanji: '話題', reading: 'わだい', meaning: 'Topik' },
    { id: 62, kanji: '相手', reading: 'あいて', meaning: 'Lawan/Pasangan' },
    { id: 63, kanji: '案内', reading: 'あんない', meaning: 'Panduan' },
    { id: 64, kanji: '意識', reading: 'いしき', meaning: 'Kesadaran' },
    { id: 65, kanji: '笑顔', reading: 'えがお', meaning: 'Senyuman' },
    { id: 66, kanji: '温室', reading: 'おんしつ', meaning: 'Rumah kaca' },
    { id: 67, kanji: '快適', reading: 'かいてき', meaning: 'Nyaman' },
    { id: 68, kanji: '会話', reading: 'かいわ', meaning: 'Percakapan' },
    { id: 69, kanji: '関心', reading: 'かんしん', meaning: 'Minat/Perhatian' },
    { id: 70, kanji: '期待', reading: 'きたい', meaning: 'Harapan/Ekspektasi' },
    { id: 71, kanji: '工夫', reading: 'くふう', meaning: 'Ide/Usaha kreatif' },
    { id: 72, kanji: '計算', reading: 'けいさん', meaning: 'Perhitungan' },
    { id: 73, kanji: '原因', reading: 'げんいん', meaning: 'Penyebab' },
    { id: 74, kanji: '効果', reading: 'こうか', meaning: 'Efek' },
    { id: 75, kanji: '困難', reading: 'こんなん', meaning: 'Kesulitan' },
    { id: 76, kanji: '才能', reading: 'さいのう', meaning: 'Bakat' },
    { id: 77, kanji: '刺激', reading: 'しげき', meaning: 'Rangsangan/Inspirasi' },
    { id: 78, kanji: '自信', reading: 'じしん', meaning: 'Percaya diri' },
    { id: 79, kanji: '証拠', reading: 'しょうこ', meaning: 'Bukti' },
    { id: 80, kanji: '制限', reading: 'せいげん', meaning: 'Batasan' },
    { id: 81, kanji: '制度', reading: 'せいど', meaning: 'Sistem' },
    { id: 82, kanji: '組織', reading: 'そしき', meaning: 'Organisasi' },
    { id: 83, kanji: '態度', reading: 'たいど', meaning: 'Sikap' },
    { id: 84, kanji: '知恵', reading: 'ちえ', meaning: 'Kebijaksanaan' },
    { id: 85, kanji: '調査', reading: 'ちょうさ', meaning: 'Penyelidikan/Survei' },
    { id: 86, kanji: '通訳', reading: 'つうやく', meaning: 'Penerjemah lisan' },
    { id: 87, kanji: '適応', reading: 'てきおう', meaning: 'Adaptasi' },
    { id: 88, kanji: '手続き', reading: 'てつづき', meaning: 'Prosedur administrasi' },
    { id: 89, kanji: '天才', reading: 'てんさい', meaning: 'Jenius' },
    { id: 90, kanji: '独立', reading: 'どくりつ', meaning: 'Mandiri' },
    { id: 91, kanji: '把握', reading: 'はあく', meaning: 'Memahami/Menguasai' },
    { id: 92, kanji: '範囲', reading: 'はんい', meaning: 'Jangkauan/Cakupan' },
    { id: 93, kanji: '避難', reading: 'ひなん', meaning: 'Evakuasi' },
    { id: 94, kanji: '負担', reading: 'ふたん', meaning: 'Beban' },
    { id: 95, kanji: '分析', reading: 'ぶんせき', meaning: 'Analisis' },
    { id: 96, kanji: '変化', reading: 'へんか', meaning: 'Perubahan' },
    { id: 97, kanji: '保証', reading: 'ほしょう', meaning: 'Jaminan' },
    { id: 98, kanji: '本気', reading: 'ほんき', meaning: 'Serius' },
    { id: 99, kanji: '認め', reading: 'みとめ', meaning: 'Pengakuan' },
    { id: 100, kanji: '矛盾', reading: 'むじゅん', meaning: 'Kontradiksi' },
    { id: 101, kanji: '面接', reading: 'めんせつ', meaning: 'Wawancara' },
    { id: 102, kanji: '約束', reading: 'やくそく', meaning: 'Janji' },
    { id: 103, kanji: '有効', reading: 'ゆうこう', meaning: 'Efektif/Valid' },
    { id: 104, kanji: '余裕', reading: 'よゆう', meaning: 'Kelonggaran' },
    { id: 105, kanji: '利益', reading: 'りえき', meaning: 'Keuntungan' },
    { id: 106, kanji: '理論', reading: 'りろん', meaning: 'Teori' },
    { id: 107, kanji: '礼儀', reading: 'れいぎ', meaning: 'Sopan santun' },
    { id: 108, kanji: '歴代', reading: 'れきだい', meaning: 'Generasi berturut-turut' },
    { id: 109, kanji: '浪費', reading: 'ろうひ', meaning: 'Pemborosan' },
    { id: 110, kanji: '割合', reading: 'わりあい', meaning: 'Persentase/Perbandingan' },
    { id: 111, kanji: '暗記', reading: 'あんき', meaning: 'Hafalan' },
    { id: 112, kanji: '意欲', reading: 'いよく', meaning: 'Motivasi' },
    { id: 113, kanji: '運営', reading: 'うんえい', meaning: 'Pengelolaan/Operasional' },
    { id: 114, kanji: '援助', reading: 'えんじょ', meaning: 'Bantuan' },
    { id: 115, kanji: '課題', reading: 'かだい', meaning: 'Tugas/Masalah' },
    { id: 116, kanji: '禁煙', reading: 'きんえん', meaning: 'Larangan merokok' },
    { id: 117, kanji: '区別', reading: 'くべつ', meaning: 'Perbedaan/Pembedaan' },
    { id: 118, kanji: '傾向', reading: 'けいこう', meaning: 'Kecenderungan' },
    { id: 119, kanji: '諦める', reading: 'あきらめる', meaning: 'Menyerah' },
    { id: 120, kanji: '預かる', reading: 'あずかる', meaning: 'Menitipkan/Menjaga' },
    { id: 121, kanji: '与える', reading: 'あたえる', meaning: 'Memberi' },
    { id: 122, kanji: '扱う', reading: 'あつかう', meaning: 'Menangani' },
    { id: 123, kanji: '溢れる', reading: 'あふれる', meaning: 'Meluap' },
    { id: 124, kanji: '余る', reading: 'あまる', meaning: 'Tersisa' },
    { id: 125, kanji: '合わせる', reading: 'あわせる', meaning: 'Mencocokkan/Menyesuaikan' },
    { id: 126, kanji: '生かす', reading: 'いかす', meaning: 'Memanfaatkan' },
    { id: 127, kanji: '苛める', reading: 'いじめる', meaning: 'Membully' },
    { id: 128, kanji: '致す', reading: 'いたす', meaning: 'Melakukan (sopan)' },
    { id: 129, kanji: '挑む', reading: 'いどむ', meaning: 'Menantang' },
    { id: 130, kanji: '浮かぶ', reading: 'うかぶ', meaning: 'Mengapung/Terbayang' },
    { id: 131, kanji: '訴える', reading: 'うったえる', meaning: 'Menuntut/Mengeluh' },
    { id: 132, kanji: '促す', reading: 'うながす', meaning: 'Mendorong' },
    { id: 133, kanji: '得られる', reading: 'えられる', meaning: 'Memperoleh' },
    { id: 134, kanji: '応じる', reading: 'おうじる', meaning: 'Merespons' },
    { id: 135, kanji: '行う', reading: 'おこなう', meaning: 'Melaksanakan' },
    { id: 136, kanji: '抑える', reading: 'おさえる', meaning: 'Menekan/Mengendalikan' },
    { id: 137, kanji: '恐れる', reading: 'おそれる', meaning: 'Takut' },
    { id: 138, kanji: '思いつく', reading: 'おもいつく', meaning: 'Terpikir' },
    { id: 139, kanji: '抱える', reading: 'かかえる', meaning: 'Menanggung/Memeluk' },
    { id: 140, kanji: '隠れる', reading: 'かくれる', meaning: 'Bersembunyi' },
    { id: 141, kanji: '重なる', reading: 'かさなる', meaning: 'Bertumpuk/Bertepatan' },
    { id: 142, kanji: '稼ぐ', reading: 'かせぐ', meaning: 'Menghasilkan uang' },
    { id: 143, kanji: '数える', reading: 'かぞえる', meaning: 'Menghitung' },
    { id: 144, kanji: '片付ける', reading: 'かたづける', meaning: 'Merapikan' },
    { id: 145, kanji: '被せる', reading: 'かぶせる', meaning: 'Menutupi' },
    { id: 146, kanji: '構う', reading: 'かまう', meaning: 'Peduli/Meladeni' },
    { id: 147, kanji: '可愛がる', reading: 'かわいがる', meaning: 'Menyayangi' },
    { id: 148, kanji: '気付く', reading: 'きづく', meaning: 'Menyadari' },
    { id: 149, kanji: '繰り返す', reading: 'くりかえす', meaning: 'Mengulang' },
    { id: 150, kanji: '加える', reading: 'くわえる', meaning: 'Menambahkan' },
    { id: 151, kanji: '削る', reading: 'けずる', meaning: 'Mengurangi/Mengikis' },
    { id: 152, kanji: '異なる', reading: 'ことなる', meaning: 'Berbeda' },
    { id: 153, kanji: '断る', reading: 'ことわる', meaning: 'Menolak' },
    { id: 154, kanji: '零れる', reading: 'こぼれる', meaning: 'Tumpah' },
    { id: 155, kanji: '避ける', reading: 'さける', meaning: 'Menghindari' },
    { id: 156, kanji: '支える', reading: 'ささえる', meaning: 'Mendukung' },
    { id: 157, kanji: '妨げる', reading: 'さまたげる', meaning: 'Menghalangi' },
    { id: 158, kanji: '仕上がる', reading: 'しあがる', meaning: 'Selesai sempurna' },
    { id: 159, kanji: '強いる', reading: 'しいる', meaning: 'Memaksa' },
    { id: 160, kanji: '従う', reading: 'したがう', meaning: 'Mengikuti/Mematuhi' },
    { id: 161, kanji: '凌ぐ', reading: 'しのぐ', meaning: 'Bertahan/Melewati' },
    { id: 162, kanji: '絞る', reading: 'しぼる', meaning: 'Memeras/Memfokuskan' },
    { id: 163, kanji: '示す', reading: 'しめす', meaning: 'Menunjukkan' },
    { id: 164, kanji: '仕分ける', reading: 'しわける', meaning: 'Memilah' },
    { id: 165, kanji: '整理する', reading: 'せいりする', meaning: 'Mengatur/Merapikan' },
    { id: 166, kanji: '責める', reading: 'せめる', meaning: 'Menyalahkan' },
    { id: 167, kanji: '育てる', reading: 'そだてる', meaning: 'Membesarkan/Memelihara' },
    { id: 168, kanji: '備える', reading: 'そなえる', meaning: 'Mempersiapkan' },
    { id: 169, kanji: '倒れる', reading: 'たおれる', meaning: 'Roboh/Jatuh' },
    { id: 170, kanji: '託す', reading: 'たくす', meaning: 'Mempercayakan' },
    { id: 171, kanji: '確かめる', reading: 'たしかめる', meaning: 'Memastikan' },
    { id: 172, kanji: '助かる', reading: 'たすかる', meaning: 'Tertolong' },
    { id: 173, kanji: '達する', reading: 'たっする', meaning: 'Mencapai' },
    { id: 174, kanji: '例える', reading: 'たとえる', meaning: 'Mengibaratkan' },
    { id: 175, kanji: '頼る', reading: 'たよる', meaning: 'Bergantung' },
    { id: 176, kanji: '近付く', reading: 'ちかづく', meaning: 'Mendekati' },
    { id: 177, kanji: '散らかる', reading: 'ちらかる', meaning: 'Berantakan' },
    { id: 178, kanji: '散らかす', reading: 'ちらかす', meaning: 'Mengotori/Mengacaukan' },
    { id: 179, kanji: '繋がる', reading: 'つながる', meaning: 'Terhubung' },
    { id: 180, kanji: '繋ぐ', reading: 'つなぐ', meaning: 'Menghubungkan' },
    { id: 181, kanji: '潰す', reading: 'つぶす', meaning: 'Menghancurkan' },
    { id: 182, kanji: '釣り合う', reading: 'つりあう', meaning: 'Seimbang' },
    { id: 183, kanji: '手伝う', reading: 'てつだう', meaning: 'Membantu' },
    { id: 184, kanji: '照る', reading: 'てる', meaning: 'Bersinar' },
    { id: 185, kanji: '整う', reading: 'ととのう', meaning: 'Tertata' },
    { id: 186, kanji: '整える', reading: 'ととのえる', meaning: 'Menata/Mempersiapkan' },
    { id: 187, kanji: '届く', reading: 'とどく', meaning: 'Sampai' },
    { id: 188, kanji: '届ける', reading: 'とどける', meaning: 'Mengirimkan' },
    { id: 189, kanji: '捕らえる', reading: 'とらえる', meaning: 'Menangkap' },
    { id: 190, kanji: '取れる', reading: 'とれる', meaning: 'Terlepas/Bisa diambil' },
    { id: 191, kanji: '流れる', reading: 'ながれる', meaning: 'Mengalir' },
    { id: 192, kanji: '慰める', reading: 'なぐさめる', meaning: 'Menghibur' },
    { id: 193, kanji: '怠ける', reading: 'なまける', meaning: 'Bermalas-malasan' },
    { id: 194, kanji: '慣れる', reading: 'なれる', meaning: 'Terbiasa' },
    { id: 195, kanji: '似合う', reading: 'にあう', meaning: 'Cocok' },
    { id: 196, kanji: '逃げる', reading: 'にげる', meaning: 'Melarikan diri' },
    { id: 197, kanji: '濁る', reading: 'にごる', meaning: 'Keruh' },
    { id: 198, kanji: '盗む', reading: 'ぬすむ', meaning: 'Mencuri' },
    { id: 199, kanji: '願う', reading: 'ねがう', meaning: 'Berharap' },
    { id: 200, kanji: '延ばす', reading: 'のばす', meaning: 'Menunda/Memperpanjang' },
    { id: 201, kanji: '省く', reading: 'はぶく', meaning: 'Menghilangkan' },
    { id: 202, kanji: '励ます', reading: 'はげます', meaning: 'Menyemangati' },
    { id: 203, kanji: '挟む', reading: 'はさむ', meaning: 'Menjepit' },
    { id: 204, kanji: '外す', reading: 'はずす', meaning: 'Melepas' },
    { id: 205, kanji: '離れる', reading: 'はなれる', meaning: 'Menjauh' },
    { id: 206, kanji: '広がる', reading: 'ひろがる', meaning: 'Menyebar' },
    { id: 207, kanji: '含む', reading: 'ふくむ', meaning: 'Mengandung' },
    { id: 208, kanji: '防ぐ', reading: 'ふせぐ', meaning: 'Mencegah' },
    { id: 209, kanji: 'ぶつかる', reading: 'ぶつかる', meaning: 'Bertabrakan' },
    { id: 210, kanji: '増やす', reading: 'ふやす', meaning: 'Menambah' },
    { id: 211, kanji: '曖昧', reading: 'あいまい', meaning: 'Samar/Tidak jelas' },
    { id: 212, kanji: '明らか', reading: 'あきらか', meaning: 'Jelas' },
    { id: 213, kanji: '荒い', reading: 'あらい', meaning: 'Kasar' },
    { id: 214, kanji: '有難い', reading: 'ありがたい', meaning: 'Bersyukur/Berharga' },
    { id: 215, kanji: '安易', reading: 'あんい', meaning: 'Mudah/Gampangan' },
    { id: 216, kanji: '意外', reading: 'いがい', meaning: 'Tak terduga' },
    { id: 217, kanji: '穏やか', reading: 'おだやか', meaning: 'Tenang' },
    { id: 218, kanji: '主な', reading: 'おもな', meaning: 'Utama' },
    { id: 219, kanji: '賢い', reading: 'かしこい', meaning: 'Pintar' },
    { id: 220, kanji: '勝手', reading: 'かって', meaning: 'Seenaknya' },
    { id: 221, kanji: '可能', reading: 'かのう', meaning: 'Memungkinkan' },
    { id: 222, kanji: '急', reading: 'きゅう', meaning: 'Mendadak' },
    { id: 223, kanji: '器用', reading: 'きよう', meaning: 'Terampil' },
    { id: 224, kanji: '気楽', reading: 'きらく', meaning: 'Santai' },
    { id: 225, kanji: '悔しい', reading: 'くやしい', meaning: 'Kesal/Menyesal' },
    { id: 226, kanji: '険しい', reading: 'けわしい', meaning: 'Curam/Keras' },
    { id: 227, kanji: '細かい', reading: 'こまかい', meaning: 'Detail/Kecil' },
    { id: 228, kanji: '盛ん', reading: 'さかん', meaning: 'Ramai/Aktif' },
    { id: 229, kanji: '失礼', reading: 'しつれい', meaning: 'Tidak sopan' },
    { id: 230, kanji: '真剣', reading: 'しんけん', meaning: 'Serius' },
    { id: 231, kanji: '地味', reading: 'じみ', meaning: 'Sederhana' },
    { id: 232, kanji: '十分', reading: 'じゅうぶん', meaning: 'Cukup' },
    { id: 233, kanji: '正直', reading: 'しょうじき', meaning: 'Jujur' },
    { id: 234, kanji: '新鮮', reading: 'しんせん', meaning: 'Segar' },
    { id: 235, kanji: '素直', reading: 'すなお', meaning: 'Penurut/Jujur' },
    { id: 236, kanji: '鋭い', reading: 'するどい', meaning: 'Tajam' },
    { id: 237, kanji: '正確', reading: 'せいかく', meaning: 'Akurat' },
    { id: 238, kanji: '退屈', reading: 'たいくつ', meaning: 'Bosan' },
    { id: 239, kanji: '確か', reading: 'たしか', meaning: 'Pasti/Yakin' },
    { id: 240, kanji: '小さな', reading: 'ちいさな', meaning: 'Kecil' },
    { id: 241, kanji: '強気', reading: 'つよき', meaning: 'Percaya diri' },
    { id: 242, kanji: '丁寧', reading: 'ていねい', meaning: 'Sopan/Teliti' },
    { id: 243, kanji: '得意', reading: 'とくい', meaning: 'Mahir' },
    { id: 244, kanji: '特別', reading: 'とくべつ', meaning: 'Spesial' },
    { id: 245, kanji: '苦手', reading: 'にがて', meaning: 'Tidak mahir' },
    { id: 246, kanji: '鈍い', reading: 'にぶい', meaning: 'Tumpul/Lambat' },
    { id: 247, kanji: '派手', reading: 'はで', meaning: 'Mencolok' },
    { id: 248, kanji: '必要', reading: 'ひつよう', meaning: 'Penting/Perlu' },
    { id: 249, kanji: '不思議', reading: 'ふしぎ', meaning: 'Aneh/Misterius' },
    { id: 250, kanji: '朗らか', reading: 'ほがらか', meaning: 'Ceria' },
    { id: 251, kanji: '真面目', reading: 'まじめ', meaning: 'Serius' },
    { id: 252, kanji: '真っ白', reading: 'まっしろ', meaning: 'Putih bersih' },
    { id: 253, kanji: '真っ暗', reading: 'まっくら', meaning: 'Gelap gulita' },
    { id: 254, kanji: '惨め', reading: 'みじめ', meaning: 'Menyedihkan' },
    { id: 255, kanji: '珍しい', reading: 'めずらしい', meaning: 'Langka' },
    { id: 256, kanji: '厄介', reading: 'やっかい', meaning: 'Merepotkan' },
    { id: 257, kanji: '優秀', reading: 'ゆうしゅう', meaning: 'Unggul' },
    { id: 258, kanji: '豊か', reading: 'ゆたか', meaning: 'Kaya/Melimpah' },
    { id: 259, kanji: '容易', reading: 'ようい', meaning: 'Mudah' },
    { id: 260, kanji: '余計', reading: 'よけい', meaning: 'Berlebihan' },
    { id: 261, kanji: '乱暴', reading: 'らんぼう', meaning: 'Kasar' },
    { id: 262, kanji: '利口', reading: 'りこう', meaning: 'Pintar' },
    { id: 263, kanji: '冷静', reading: 'れいせい', meaning: 'Tenang' },
    { id: 264, kanji: '論理的', reading: 'ろんりてき', meaning: 'Logis' },
    { id: 265, kanji: '我儘', reading: 'わがまま', meaning: 'Egois' },
    { id: 266, kanji: '鮮やか', reading: 'あざやか', meaning: 'Cerah/Mencolok' },
    { id: 267, kanji: '怪しい', reading: 'あやしい', meaning: 'Mencurigakan' },
    { id: 268, kanji: '新た', reading: 'あらた', meaning: 'Baru' },
    { id: 269, kanji: '意地悪', reading: 'いじわる', meaning: 'Jahil/Jahat' },
    { id: 270, kanji: '完全', reading: 'かんぜん', meaning: 'Sempurna/Lengkap' },
    { id: 271, kanji: '奇妙', reading: 'きみょう', meaning: 'Aneh' },
    { id: 272, kanji: 'くどい', reading: 'くどい', meaning: 'Bertele-tele' },
    { id: 273, kanji: 'けちな', reading: 'けちな', meaning: 'Pelit' },
    { id: 274, kanji: '心強い', reading: 'こころづよ', meaning: 'Meyakinkan' },
    { id: 275, kanji: '爽やか', reading: 'さわやか', meaning: 'Segar' },
    { id: 276, kanji: '重大', reading: 'じゅうだい', meaning: 'Penting/Serius' },
    { id: 277, kanji: '慎重', reading: 'しんちょう', meaning: 'Hati-hati' },
    { id: 278, kanji: '狭い', reading: 'せまい', meaning: 'Sempit' },
    { id: 279, kanji: '粗末', reading: 'そまつ', meaning: 'Sederhana/Buruk' },
    { id: 280, kanji: '大事', reading: 'だいじ', meaning: 'Penting' },
    { id: 281, kanji: '調子', reading: 'ちょうし', meaning: 'Kondisi' },
    { id: 282, kanji: '適切', reading: 'てきせつ', meaning: 'Tepat' },
    { id: 283, kanji: '滑らか', reading: 'なめらか', meaning: 'Halus/Lancar' },
    { id: 284, kanji: '賑やか', reading: 'にぎやか', meaning: 'Ramai' },
    { id: 285, kanji: '営業', reading: 'えいぎょう', meaning: 'Penjualan/Bisnis' },
  ];
